### ISSUE TITLE
windows node trying to pull Linux nginx-ingress controller image

### ISSUE THREAD

**Issue by llyons** [kubernetes-sigs/sig-windows-tools#100]
Hi,  We have a 2 linux, 1 windows node cluster setup.   The linux nodes work and the windows node shows ready from a kubernetes cluster perspective.   However when trying to setup the nginx-ingress controller, the windows node is trying to pull the linux image

Normal   Scheduled  11m                  default-scheduler       Successfully assigned nginx-ingress/nginx-ingress-tr77s to aabrw-kuber03
  Normal   Pulling    9m30s (x4 over 10m)  kubelet, aabrw-kuber03  Pulling image "nginx/nginx-ingress:1.8.1"
  Warning  Failed     9m29s (x4 over 10m)  kubelet, aabrw-kuber03  Error: ErrImagePull
  Warning  Failed     52s (x41 over 10m)   kubelet, aabrw-kuber03  Error: ImagePullBackOff

the other nodes (linux) are running nginx-ingress.

[lance_lyons@OLH.LOCAL@aabrl-kuber01 daemon-set]$ kubectl get pods --namespace nginx-ingress
NAME                            READY   STATUS             RESTARTS   AGE
nginx-ingress-94d765bfd-64p6q   1/1     Running            2          6h30m
nginx-ingress-gs4mt             1/1     Running            2          27m
nginx-ingress-lbxp4             1/1     Running            0          42m
nginx-ingress-tr77s             0/1     ImagePullBackOff   0          11m

How do we force the windows node to pull the right image?

**Comment by lippertmarkus** [comment]
The nginx ingress controller only runs on Linux. You need to add the `kubernetes.io/os=linux` `nodeSelector` to Linux-only workloads like this as described in the docs: https://kubernetes.io/docs/setup/production-environment/windows/user-guide-windows-containers/#ensuring-os-specific-workloads-land-on-the-appropriate-container-host

**Comment by llyons** [comment]
Thanks.  We have this working now.  thanks for the info.
