### ISSUE TITLE
Add automation for building kubeadm related containers

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/sig-windows-tools#110]
There is currently a github action for building kube-proxy: https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/.github/workflows/kube-proxy.yml

There should be a pipeline for building and publishing flannel images as well.  Should be able to use kube-proxy as an example

**Comment by vitaliy-leschenko** [comment]
I will try to do it

**Comment by benmoss** [comment]
Yeah, I think the only reason we didn't do this was because flannel releases once in a blue moon (aka very rarely)

**Comment by vitaliy-leschenko** [comment]
@jsturtevant please review my PR to fix the issue

**Comment by jsturtevant** [comment]
fixed by #111
