### ISSUE TITLE
This line leaves a trailing " which causes an error

### ISSUE THREAD

**Issue by fourpastmidnight** [kubernetes-sigs/sig-windows-tools#115]
While attempting to get my Windows Server 2019 2004 (10.0.19041.508) server configured as a Kubernetes node and joined to the cluster, I endured many hardships getting Kubelet to run stably.

One such issue I ran into is the following line:

https://github.com/kubernetes-sigs/sig-windows-tools/blob/1f4abb21ff35d68b1b2c5d49eefb2daa05bc98d8/kubeadm/scripts/PrepareNode.ps1#L68

This line of code leaves a trailing `"`&mdash;and when there are more arguments which follow the ones contained in `kubeadm-flags.env` (which are configured on line 76 in the same script), Kubelet may fail to run. In my case, I was passing in a quote-delimited value for `--cert-dir`:

```
C:\k\kubelet.exe $global:KubeletArgs --cert-dir="C:\var\lib\kubelet\pki" ...
```

With the trailing quote I mentioned (which is now part of `$global:KubeletArgs`, this gets expanded to:

```
C:\k\Kubelet.exe --network-plugin=cni --pod-infra-container-image=mcr.microsoft.com/oss/kubernetes/pause:1.3.0" --cert-dir="C:\var\lib\kubelet\pki" ...
```

So as you can see, I actually end up with a string such as `"--cert-dir="`, and later, after the value, another string, `" --some-other-arg=some_value --and-another-arg=another_value"`, etc. until the next `"`. This is obviously an invalid command line for Kubelet.

**Comment by marosset** [comment]
Hmm,

On a Windows Server 2019 node (10.0.17763.1518) I see the following behavior. 

```powershell
PS C:\Users\user> type C:\var\lib\kubelet\kubeadm-flags.env
KUBELET_KUBEADM_ARGS="--network-plugin=cni --pod-infra-container-image=mcr.microsoft.com/oss/kubernetes/pause:1.3.0"

PS C:\Users\user> $FileContent = Get-Content -Path "/var/lib/kubelet/kubeadm-flags.env"
PS C:\Users\user> $global:KubeletArgs = $FileContent.Trim("KUBELET_KUBEADM_ARGS=`"")
PS C:\Users\user> $Global:KubeletArgs
--network-plugin=cni --pod-infra-container-image=mcr.microsoft.com/oss/kubernetes/pause:1.3.0
```

I wonder if something changed here on Windows Server, version 2004

**Comment by marosset** [comment]
Also, I don't believe mcr.microsoft.com/oss/kubernetes/pause:1.3.0 has an image that will work on Windows Server, Version 2014.
This should be using mcr.microsoft.com/oss/kubernetes/pause:1.4.1 or later.

Let me file another issue.

**Comment by marosset** [comment]
https://github.com/kubernetes-sigs/sig-windows-tools/issues/116 for the incorrect pause image

**Comment by fourpastmidnight** [comment]
Here's the contents `kubeadm-flags.env` file that was present when I started on this endeavor:

```
KUBELET_KUBEADM_ARGS="--network-plugin=cni --pod-infra-container=mcr.microsoft.com/oss/kubernetes/pause:1.3.0"
```

So, after running the code:

https://github.com/kubernetes-sigs/sig-windows-tools/blob/8f6890d6fc6e36aff229c4a895a958576f297a77/kubeadm/scripts/PrepareNode.ps1#L68

you're left with:

```
--network-plugin=cni --pod-infra-container=mcr.microsoft.com/oss/kubernetes/pause:1.3.0"
```

Note the trailing slash. And in `PrepareNode.ps1`, these "trimmed" arguments are stuffed into `$global:kubeletargs`, and on line 76:

https://github.com/kubernetes-sigs/sig-windows-tools/blob/8f6890d6fc6e36aff229c4a895a958576f297a77/kubeadm/scripts/PrepareNode.ps1#L76

And as you can see, more arguments follow `$global:kubeargs`, which caused a headache for me.

As for the pause image not working on Windows Server 2019 2004&mdash;yes, you're correct. But I didn't know about the existence of v1.4.1, so I built my own, specifically for the version of Windows Server I'm running, 10.0.19041.508. Besides, it's a very fast image to build 😉

**Comment by fourpastmidnight** [comment]
I suppose, alternatively, line 68 could be as follows:

```
$global:KubeletArgs = $FileContent.Trim('KUBELET_KUBEADM_ARGS=').Trim('"');
```

Or even

```
$global:KubeletArgs = $FileCountent.Substring('KUBELET_KUBEADM_ARGS='.Length).Trim('"')
```

This would _ensure_ that all "wrapping" quotes will be removed.

**Comment by marosset** [comment]
@fourpastmidnight Either of those work. Would you like to open a PR for this or would you like me to?

**Comment by fourpastmidnight** [comment]
I can do that. Thanks!

**Comment by jsturtevant** [comment]
#118 fixed this

/close
