### ISSUE TITLE
Update docker files to use buildx to support multiple Windows OS

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/sig-windows-tools#123]
**Is your feature request related to a problem? Please describe.**

Build upon #111 to convert the dockerfiles to use buildx so we can build versions for [supported Windows OS's](https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#windows-os-version-support).  This would solve #93 and #90 

References:
pause image: https://github.com/kubernetes/kubernetes/blob/9a57dc20a98dcc7a6b2bd1323d4e27f84477cd1b/build/pause/Dockerfile_windows
test images: https://github.com/kubernetes/kubernetes/pull/93889

**Describe the solution you'd like**

There would be the following images:

    sigwindowstools/flannel:v0.12 (multi arch manifest that points to the latest of the following images)

    sigwindowstools/flannel:v0.12-2019-{build_tag}

    sigwindowstools/flannel:v0.12-1909-{build_tag}

    sigwindowstools/flannel:v0.12-2004-{build_tag}

    sigwindowstools/flannel:v0.13 (multi arch manifest that points to the latest of the following images)

    sigwindowstools/flannel:v0.13-2019-{build_tag}

    sigwindowstools/flannel:v0.13-1909-{build_tag}

    sigwindowstools/flannel:v0.13-2004-{build_tag}

**Describe alternatives you've considered**
Setting up windows servers for each version. This requires to much maintenance and costs.

**Additional context**

**Comment by vitaliy-leschenko** [comment]
I tried to do it in my repo (https://github.com/vitaliy-leschenko/win-flannel) but it was failed.
![image](https://user-images.githubusercontent.com/12435135/98446834-9ad9a100-2131-11eb-88f6-4e8a72fe9199.png)

I don't understand why it works for `pause` image.

**Comment by vitaliy-leschenko** [comment]
I did it! @jsturtevant please re-review last changes at #111

**Comment by vitaliy-leschenko** [comment]
I think this issue requires update kube-proxy too. I can do it after finish PR (#111) with flannel.

**Comment by vitaliy-leschenko** [comment]
I added kubeproxy images for all windows server versions also in #111.
