### ISSUE TITLE
Communication with services sometimes failed

### ISSUE THREAD

**Issue by vitaliy-leschenko** [kubernetes-sigs/sig-windows-tools#127]
**Describe the bug**
Windows pods can't communicate with services if target pod stay on different Windows node.
Maybe this is duplicate of another issues but symptoms are a little bit difference.

Windows pods can communicate with services from pods that run on Linux without any problem.
Linux pods can communicate with services from pods that run on Windows without any problem.

**To Reproduce**
1. Setup new cluster with 2 linux and 2 windows nodes using [PrepareNode.ps1](https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/kubeadm/scripts/PrepareNode.ps1)
2. Apply [yaml](https://vitaliyorgstorage.azureedge.net/9d4196ab-1c3c-4efb-b065-b643384f1832/github/sample.yaml)
 It creates 2 daemonsets `iis` (on windows) and `nginx` (on linux) and 2 services for each daemonset.
3. Try to connect to one of `iis` pods and curl:
 curl -Ik nginx.issues.svc.cluster.local  <-- will be success in 100% cases
 curl -Ik iis.isses.svc.cluster.local <-- will be success only in cases when it tries to curl from pod that runs on the same node.

**Expected behavior**
I expect that `curl -Ik iis.isses.svc.cluster.local` will be success in 100% cases

**Kubernetes (please complete the following information):**
 - Windows Server version: 1809 (10.0.17763.1554)
 - Kubernetes Version: 1.19.0 - 1.19.4
 - CNI: flannel 0.13 vxlan

**Additional context**
All pods can ping each others by IP address.
All windows pods can curl from the Internet and ping each other.
Windows pods can curl from windows pods on different nodes by IP address but failed when I try to curl by Service name or Service IP address.

My PR #111 doesn't affect it because it reproduced without it.

**Comment by vitaliy-leschenko** [comment]
I tried yaml from step 2 on baremetal cluster (1.17.0) created by https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/kubeadm/KubeCluster.ps1 and this issue doesn't reproduced.

**Comment by vitaliy-leschenko** [comment]
It is truly interesting  but the issue doesn't reproduced on Windows Server 1809 (10.0.17763.1294)

**Comment by vitaliy-leschenko** [comment]
It is look like a Windows issue.

**Comment by daschott** [comment]
Is this still active?

**Comment by vitaliy-leschenko** [comment]
@daschott Yes, it is.

**Comment by vitaliy-leschenko** [comment]
It looks like in 10.0.17763.1999 this issues was fixed. Maybe in one of previous updates but it doesn't matter. Currently we can use latest updates and don't have the issue.
