### ISSUE TITLE
Crashloopbackoff for flannel-ds-windows pod due to "objectNotFound" error throwed from the powershell script

### ISSUE THREAD

**Issue by Celthi** [kubernetes-sigs/sig-windows-tools#129]
**Describe the bug**
The flannel-ds-windows pod met "ObjectNotFound" error when running the `run.ps1` script and failed to join a Windows node into a k8s cluster.

```
[root@tec-l-014627 admin]# kubectl logs kube-flannel-ds-windows-amd64-84gvv -n kube-system

    Directory: C:\host\k


Mode                LastWriteTime         Length Name                          
----                -------------         ------ ----                          
d-----        12/1/2020   7:25 AM                flannel                       


    Directory: C:\host\k\flannel\var\run\secrets\kubernetes.io


Mode                LastWriteTime         Length Name                          
----                -------------         ------ ----                          
d-----        12/1/2020   7:25 AM                serviceaccount                
Configuring CNI for docker
Set-Content : Could not find a part of the path 
'C:\host\etc\cni\net.d\10-flannel.conf'.
At C:\etc\kube-flannel-windows\run.ps1:26 char:3
+   Set-Content -Path /host/etc/cni/net.d/10-flannel.conf ($cniJson | C ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\host\etc\cni\net.d\10-flanne 
   l.conf:String) [Set-Content], DirectoryNotFoundException
    + FullyQualifiedErrorId : GetContentWriterDirectoryNotFoundError,Microsoft 
   .PowerShell.Commands.SetContentCommand
 ```

**To Reproduce**

**Expected behavior**
The `Set-Content` will succeed and the Windows machine joins the cluster.
**Kubernetes (please complete the following information):**
 - Windows Server version:
10.0.17763.1282
 - Kubernetes Version:
Linux control node is 1.18
Windows is 1.19
 - CNI:

**Additional context**

**Comment by marosset** [comment]
@Celthi Which deployment files are us using for the flannel ds and where are you getting the files from?
Host-gw or overlay and from master or a release?

I would expect https://github.com/kubernetes-sigs/sig-windows-tools/blob/0cfd92a65e8910d9e97507c2f7df79a410cc66d1/kubeadm/flannel/flannel-overlay.yml#L14 to create all of the directories needed for the Set-Content call to succeed.

**Comment by Celthi** [comment]
@marosset Thanks for the prompt reply. I'm following the page in https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/
So the deployment file is from `kubectl apply -f https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/flannel-overlay.yml`
It seems there is `mkdir -force /host/etc/cni/net.d` in the file, but it still failed.

**Comment by Celthi** [comment]
@marosset After several trials, I found the cause of this error. There is a shortcut folder named `etc` in the C: disk. The `mkdir -force /host/etc/cni/net.d` fails silently without creating the folder. After deleting the folder shortcut named `etc`. The error is gone. I don't understand the deep reason for this cause. It may be related to the Windows system. 
I think for this kind of error, the script here cannot handle it. So I'll close this issue. And may new comer see this issue if they meet the same error.
