### ISSUE TITLE
Waiting for CNI file

### ISSUE THREAD

**Issue by johan-smits** [kubernetes-sigs/sig-windows-tools#133]
**Describe the bug**
When running with AWS EKS cluster and the default CNI it keeps waiting
**To Reproduce**
1. https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html
2. `curl -L https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/kube-proxy.yml | sed 's/VERSION/v1.18.12/g' | kubectl apply -f -`
3. I skipped the flanel because I use the amazon-k8s-cni

**Expected behavior**
That the kube-proxy would start normally

**Kubernetes (please complete the following information):**
 - Windows Server version: Windows_Server-2019-English-Core-EKS_Optimized-1.18-2020.11.12
 - Kubernetes Version: 1.18 (eks.2)
 - CNI: amazon-k8s-cni:v1.7.5

**Additional context**
Unable to have a loadbalancer route data to other pods then the Windows ones. It is a mixed environment of Linux and Windows nodes.

**Comment by marosset** [comment]
HI @johan-smits 

The kube-proxy.yml deployment file referenced there has some assumptions about how the node was configured baked in that assume this guide was followed https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/#joining-a-windows-worker-node

I have not tried to configure Windows nodes in EKS but you probably need to find some EKS specific guidance for running kube-proxy if isn't configured automatically.

**Comment by johan-smits** [comment]
@marosset thanks for the reply, but the node is joined already and working in the cluster. I just don't use flanel.

**Comment by marosset** [comment]
Hi @johan-smits 
There are assumptions beyond just using flannel.

The kube-proxy deployment file referenced in those tutorials assumes that CNI config files are added to /etc/cni/net.d on the node. 

https://github.com/kubernetes-sigs/sig-windows-tools/blob/9aa36e43ef71947b263464b3e657e50340769315/kubeadm/kube-proxy/kube-proxy.yml#L14

Another assumption is that  the script assumes the wins service from rancher is installed on the node.

You will likely need to find EKS specific guidance on how to get kube-proxy running on your nodes.

**Comment by johan-smits** [comment]
@marosset thanks for the reply, so this kube-proxy is not compatible or you mean the script needs tweaking?

**Comment by marosset** [comment]
The way this particular deployment file deploys kube-proxy is not compatible.

kube-proxy itself it just a binary that gets released with other binaries and can be found at locations like https://dl.k8s.io/v1.19.5/bin/windows/amd64/kube-proxy.exe

Can you log into one of the Windows nodes in your EKS cluster and check if there is a process named kube-proxy running on the node? A lot of time Windows deployments do you run kube-proxy inside a pod but instead run it as a service directly on the machine.
I would be really surprised if this wasn't running already.
