### ISSUE TITLE
Windows pod resource cannot access Internet

### ISSUE THREAD

**Issue by Sirius2016** [kubernetes-sigs/sig-windows-tools#137]
Through flannel- overlay.yml Deploy network configuration
Windows pod resource cannot access Internet

Linux and windows mixed environment：
![image](https://user-images.githubusercontent.com/23203953/103335261-6f2ec380-4aaf-11eb-99fd-0d9882149498.png)

kubectl get pods：
![image](https://user-images.githubusercontent.com/23203953/103335218-56261280-4aaf-11eb-9e5b-0d02086a4274.png)

Windows pod resource cannot access Internet:
![image](https://user-images.githubusercontent.com/23203953/103335178-3989da80-4aaf-11eb-837f-d82bb849cabf.png)

**Comment by Sirius2016** [comment]
DNS parsing is normal:
![image](https://user-images.githubusercontent.com/23203953/103335412-d0ef2d80-4aaf-11eb-860e-3b291b502557.png)

**Comment by vitaliy-leschenko** [comment]
@Sirius2016, ping doesn't work. It is known issue. Please try to use curl instead of this:
```
curl -Ikv www.google.com
```

**Comment by Sirius2016** [comment]
> @Sirius2016, ping doesn't work. It is known issue. Please try to use curl instead of this:
> 
> ```
> curl -Ikv www.google.com
> ```


@vitaliy-leschenko
![image](https://user-images.githubusercontent.com/23203953/103337559-bec4bd80-4ab6-11eb-992e-999c22637e04.png)

**Comment by Sirius2016** [comment]
@vitaliy-leschenko 
windows server version info:
![image](https://user-images.githubusercontent.com/23203953/103337671-04818600-4ab7-11eb-9081-84470bd68d65.png)

**Comment by vitaliy-leschenko** [comment]
i'm sorry. use curl.exe if you run it from powershell.
