### ISSUE TITLE
Add test signal for kubeadm install

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/sig-windows-tools#14]
As a kubeadm maintainers team, we would like to have a signal wrt bootstrap windows nodes with kubeadm in the kubeadm [test grid](https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm) 

There are logistic to be addressed, but this issue aims to start a joint effort for getting this in place hopefully during the 1.17 cycle

/sig cluster-lifecycle
/cc @neolit123

**Comment by neolit123** [comment]
/remove-lifecycle stale
There is a chance we can use cluster api aws for this.

**Comment by neolit123** [comment]
/close
test signal is in place:
https://k8s-testgrid.appspot.com/sig-windows#kubeadm-windows-gcp-k8s-stable

making it green is WIP.

**Comment by fabriziopandini** [comment]
great! thanks!
