### ISSUE TITLE
Windows pods cannot access hosts on local network

### ISSUE THREAD

**Issue by TonyNoble** [kubernetes-sigs/sig-windows-tools#141]
**Describe the bug**
On a freshly-built cluster with Centos master node and Windows 2019 Core worker nodes, pods started on the worker nodes are unable to connect to hosts on our local network.

**To Reproduce**
1. Run windows webserver demo: https://kubernetes.io/docs/setup/production-environment/windows/user-guide-windows-containers/
2. Connect to one of the pods created: `kubectl exec -it <pod-name> -- powershell`
3. Verify outside world connectivity: 
```
PS C:\> curl www.google.com -UseBasicParsing -Method:Head

StatusCode        : 200
StatusDescription : OK
```
4. Attempt to connect to host on local network:
```
PS C:\> nslookup my.local.application.host
Server:  kube-dns.kube-system.svc.cluster.local
Address:  10.96.0.10

Non-authoritative answer:
Name:    my.local.application.host
Address:  10.105.166.21

PS C:\> curl https://10.105.166.21 -UseBasicParsing -Method:Head
curl : Unable to connect to the remote server
At line:1 char:1
+ curl https://10.105.166.21 -UseBasicParsing -Method:Head
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

```

**Expected behavior**
`curl http:// my.local.application.host` should connect and retrieve data

**Kubernetes (please complete the following information):**
 - Windows Server version: 2019 Core, build 1809
 - Kubernetes Version: 1.20.2
 - CNI: flannel-overlay, v0.13.0

**Additional context**

**Comment by jsturtevant** [comment]
@TonyNoble Overlay in Windows has a few restrictions: https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#cni-plugins.  If you need that type of routing you can use the host-gw or a different CNI

In particular Flannel overlay node -> pod communication isn't supported.  I believe this means that although you might be able to get a packet to the node it wouldn't be able to return to the pod.

@daschott @jocelynberrendonner for confirmation

**Comment by JocelynBerrendonner** [comment]
@TonyNoble, overlay networks on Windows don't allow PODs to communicate with distant hosts on the underlay network (doing this kinda breaks the principle of VXLAN isolation). That said, PODs can communicate with the host they run on provided a Host Route policy is applied (either to the network or to the endpoints). Local communication was enabled to allow Kubernetes health probes to work properly. I believe Flannel applies the Host Route policy by default. So, you should be able to communicate from the local host to the container, but you won't be able to communicate from distant hosts. Can you share additional information on the scenario that requires communication with distant nodes, please?

**Comment by TonyNoble** [comment]
Apologies - I hadn't seen that this had updated, for some reason.  Can we re-open?

To clarify, I'm not talking about the pod being able to reach the host, I'm talking about, for example:

* Local k8s cluster running on 10.105.1.1 -> 10.105.1.4 (master + 1 linux and 2 windows worker nodes)
* Local gitlab instance running standalone on 10.105.2.1

The behaviour I'm seeing is:
* Pods running on the linux nodes can reach gitlab instance (via ssh or https)
* Pods running on the windows nodes timeout when attempting to reach gitlab instance, except:
* * Flannel pods *can*.

If it is by design that vxlan implementations can't talk to the underlying subnet, then I'm not sure why the linux node-based pods can do it.
