### ISSUE TITLE
PrepareNode.ps1  is not capable of bootstrapping a Windows node properly

### ISSUE THREAD

**Issue by ag3man** [kubernetes-sigs/sig-windows-tools#142]
**Describe the bug**
PrepareNode.ps1 is using curl -Lo whereas the default Windows curl using powershell Invoke-Webrequest and does not have curl -Lo capabilities 

```
PS C:\Users\Administrator> curl -?

NAME
    Invoke-WebRequest

SYNTAX
    Invoke-WebRequest [-Uri] <uri> [-UseBasicParsing] [-WebSession <WebRequestSession>] [-SessionVariable <string>] [-Credential
    <pscredential>] [-UseDefaultCredentials] [-CertificateThumbprint <string>] [-Certificate <X509Certificate>] [-UserAgent
    <string>] [-DisableKeepAlive] [-TimeoutSec <int>] [-Headers <IDictionary>] [-MaximumRedirection <int>] [-Method {Default | Get
    | Head | Post | Put | Delete | Trace | Options | Merge | Patch}] [-Proxy <uri>] [-ProxyCredential <pscredential>]
    [-ProxyUseDefaultCredentials] [-Body <Object>] [-ContentType <string>] [-TransferEncoding {chunked | compress | deflate | gzip
    | identity}] [-InFile <string>] [-OutFile <string>] [-PassThru]  [<CommonParameters>]
```

ERROR received
```
Downloading https://dl.k8s.io/v1.20.0/bin/windows/amd64/kubeadm.exe to C:\k\kubeadm.exe
Downloading https://github.com/rancher/wins/releases/download/v0.0.4/wins.exe to C:\k\wins.exe
DownloadFile : Download https://github.com/rancher/wins/releases/download/v0.0.4/wins.exe failed
At C:\Users\Administrator\PrepareNode.ps1:70 char:1
+ DownloadFile "$global:KubernetesPath\wins.exe" https://github.com/ran ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DownloadFile

```

**To Reproduce**
Deploy windows worker node with the following image in AWS and follow h[ttps://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/ ](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/)
wit the following AMI
ami-0a856f60a16a36774 
Windows_Server-2004-English-Core-ContainersLatest-2021.01.13
amazon/Windows_Server-2004-English-Core-ContainersLatest-2021.01.13

**Expected behavior**
PrepareNode.ps1 to not error out.

**Kubernetes (please complete the following information):**
 - Windows Server version:  Windows_Server-2004-English-Core-ContainersLatest-2021.01.13
 - Kubernetes Version: v1.20.0
 - CNI: flannel VXLAN

**Additional context**

**Comment by neolit123** [comment]
> Windows_Server-2004-English-Core-ContainersLatest-2021.01.13

is this version of Windows Server even supported?
you should ask in #sig-windows on k8s slack.

Invoke-WebRequest is slow:
https://blog.jourdant.me/post/3-ways-to-download-files-with-powershell

you could try creating a wrapper for curl that uses:
Start-BitsTransfer

or just download a compiled CURL.exe that has the full features.

**Comment by vitaliy-leschenko** [comment]
Windows 10 (or Windows Server 2019+) has build-in tool curl.exe.
At the same time Windows PowerShell has `curl` as alias to Invoke-WebRequest.

**Comment by ag3man** [comment]
After further testing it looks like curl.exe DOES exist and I am able to use it. I am going to close this myself. I am having other issues bootstrapping, but I can raise another issue.
