### ISSUE TITLE
Windows Server 2019 Builds and SIG Tools Powershell script incompatibilities

### ISSUE THREAD

**Issue by KanishkT123** [kubernetes-sigs/sig-windows-tools#143]
**Describe the bug**
`latest` is incompatible with Windows Server 2019 Build 1809 but `v0.1.2` appears to work correctly.

**To Reproduce**
While working with this repository, we found the following behavior:
1. Set up a Kubernetes control node
2. Connect a Windows Virtual Machine running WS 2019 Build 1809 [Version 10.0.17763.805] as a worker node
3. The `latest` version of the SIG tools does not allow the Virtual machine to join the cluster
4. Changing the tags from latest `v0.1.2`  and the container image to `sigwindowstools/kube-proxy:v1.19.4.1809` resolves the issue

**Expected behavior**
These steps should not be needed, as the `latest` version of the SIG Windows Tools should work with the currently supported build 1809, as per the instructions here: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/

**Kubernetes (please complete the following information):**
 - Windows Server version: WS 2019 Build 1809 [Version 10.0.17763.805] 
 - Kubernetes Version: `v1.19.4`
 - CNI: flannel

**Additional context**
I am still in the middle of experimentation, and will add more details as I find them. Additionally, we believe that WS 2019 build 1903 does work with the `latest` release, `v0.1.5`

**Comment by jsturtevant** [comment]
What part of the joining fails? Can you give an error message?  

The job https://testgrid.k8s.io/sig-windows-releases#kubeadm-windows-gcp-k8s-stable Is using the `latest` github files and the cluster is coming up.  from the logs:

```
configmap/kube-flannel-cfg created
daemonset.apps/kube-flannel-ds created
+ curl -sL https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/kube-proxy.yml
+ sed s/VERSION/v1.20.4/g
+ kubectl apply -f -
configmap/kube-proxy-windows created
daemonset.apps/kube-proxy-windows created
+ kubectl apply -f https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/flannel-overlay.yml
configmap/kube-flannel-windows-cfg created
daemonset.apps/kube-flannel-ds-windows-amd64 created
```

The latest images are multi arch so should work on 1809+
