### ISSUE TITLE
Windows Development Environments for upstream (onboarding project)

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/sig-windows-tools#145]
**Is your feature request related to a problem? Please describe.**
Add a recipe to this repo on how to setup a minimal windows cluster w/ a Kind control plane

1) Read https://github.com/kubernetes/community/blob/master/sig-windows/CONTRIBUTING.md 
2) start hacking 

**Describe the solution you'd like** 

normal k8s clusters: 
```                                     <---- sched
etcd < --- k8 apiserver   <---- kcm
                                           <--- kubelet linux
                                           <--- kubelet linux
                                           <--- kubelet linux
                                           <--- kubelet linux                                          
```

WINDOWS k8s clusters: 
```                                     <---- sched
etcd < --- k8 apiserver   <---- kcm
                                           <--- kubelet windows **** add instructions for this ****
                                           <--- kubelet linux
```

# overall steps
1) kind create cluster
- learn about kind
- run e2e tests or sonobuoy tests, see if they work 
- read about kubeadm join , kubeadm join tokens
- to cheat you can use https://github.com/jayunit100/k8sprototypes/blob/master/kind/kind-local-up.sh 
2) install a cni provider (calico, antrea)
- read the basics of how cnis work, look at docs for calico / antrea on windows
3) create a windows VM
- get join token from calico control plane (docker exec into it, ip a,  `kubeadm token create --print-join-command`) 
- `kubeadm join 172.18.0.2:6443 --token 0fjo41.martt93l9aa9m5tw     --discovery-token-ca-cert-hash sha256:323c5d2b7182aea16a7539d6c907c13d63abf9414832d001cffc4eebb3a46807`

4) install kubelet.exe and other windows stuff on it (contianerd...)
5) kubeadm join that windows VM to the kind cluster 

# bonus 

wrap in TF/Vagrant/...

**Comment by jayunit100** [comment]
Next steps @FriedrichWilken will be figuring out how to get Vagrant to run powershell or winRM commands remotely to automate the windows steps !

**Comment by FriedrichWilken** [comment]
The image that I am using for the win server 19 vm ([Github](https://github.com/StefanScherer/packer-windows), [Vagrant](https://app.vagrantup.com/StefanScherer/boxes/windows_2019) has removed ssh support and instead uses [winRM](https://github.com/criteo/vagrant-winrm), it says in the githubs readme. The issue is, that winRM can only send commands to the machine but does not answer. This can lead to situations where you get stuck because actually windows is waiting for further input, but you can't see that nor run further commands. WinRM just waits 'forever'.

**Comment by FriedrichWilken** [comment]
[This](https://github.com/FriedrichWilken/KubernetesOnWindows) is what I have so far.

**Comment by jsturtevant** [comment]
have you seen: https://github.com/PatrickLang/windows-k8s-lab?

**Comment by FriedrichWilken** [comment]
> have you seen: https://github.com/PatrickLang/windows-k8s-lab?

Yes, and it gave me some good ideas. But Patrick worked with building a Windows image while I am (for now) trying to archive all only with a vagrantfile. The idea is, that it is easy to look into the vagrantfile to see what is actually going on. It looks like he also stumbled over rebooting Windows from a vagrantfile ("# TODO reboot") between provisioning steps.

**Comment by marosset** [comment]
> The image that I am using for the win server 19 vm ([Github](https://github.com/StefanScherer/packer-windows), [Vagrant](https://app.vagrantup.com/StefanScherer/boxes/windows_2019) has removed ssh support and instead uses [winRM](https://github.com/criteo/vagrant-winrm), it says in the githubs readme. The issue is, that winRM can only send commands to the machine but does not answer. This can lead to situations where you get stuck because actually windows is waiting for further input, but you can't see that nor run further commands. WinRM just waits 'forever'.

Ugh :(
I ran into issues with WinRM and reboots while trying to build our golden images for aks-egnine.
The issue we were facing was that right after installing Hyper-V there was a race between when the WinRM service would start and when Hyper-V would swap out the network interface / adding a vSwitch.

We were able to solve that race by delaying the start of the WinRM service on the machine
https://github.com/Azure/aks-engine/blob/47c439d1e8891a1cc63ced39332418f1506e6a41/vhd/packer/configure-windows-vhd.ps1#L262

Not sure if that helps at all but I feel your pain here...

**Comment by FriedrichWilken** [comment]
> > The image that I am using for the win server 19 vm ([Github](https://github.com/StefanScherer/packer-windows), [Vagrant](https://app.vagrantup.com/StefanScherer/boxes/windows_2019) has removed ssh support and instead uses [winRM](https://github.com/criteo/vagrant-winrm), it says in the githubs readme. The issue is, that winRM can only send commands to the machine but does not answer. This can lead to situations where you get stuck because actually windows is waiting for further input, but you can't see that nor run further commands. WinRM just waits 'forever'.
> 
> Ugh :(
> I ran into issues with WinRM and reboots while trying to build our golden images for aks-egnine.
> The issue we were facing was that right after installing Hyper-V there was a race between when the WinRM service would start and when Hyper-V would swap out the network interface / adding a vSwitch.
> 
> We were able to solve that race by delaying the start of the WinRM service on the machine
> https://github.com/Azure/aks-engine/blob/47c439d1e8891a1cc63ced39332418f1506e6a41/vhd/packer/configure-windows-vhd.ps1#L262
> 
> Not sure if that helps at all but I feel your pain here...

Oh man, the image building is just too advanced for me right now. I am just getting started. But will look into that repo again when I am ready to learn about that!

**Comment by FriedrichWilken** [comment]
https://github.com/FriedrichWilken/KubernetesOnWindows
So close. 
```
vagrant@master:~$ kubectl get nodes
NAME     STATUS     ROLES                  AGE   VERSION
master   Ready      control-plane,master   57m   v1.20.4
winw1    NotReady   <none>                 47m   v1.20.4
```

**Comment by FriedrichWilken** [comment]
I think this is now version 1.0. From here on we could create a roadmap for moving to Containerd, Kubernetes 1.21.0 (currently using 1.20.4), modularize CNI and start supporting Ansible and Calico. 
Also needs tests for MacOS and Windows.

https://github.com/FriedrichWilken/KubernetesOnWindows

**Comment by jayunit100** [comment]
tested and working for me. 
thanks friedrich !
```
vagrant@master:~$ kubectl get pods -A
NAMESPACE     NAME                                  READY   STATUS    RESTARTS   AGE
kube-system   coredns-74ff55c5b-k9gcb               1/1     Running   0          12h
kube-system   coredns-74ff55c5b-n67dv               1/1     Running   0          12h
kube-system   etcd-master                           1/1     Running   0          12h
kube-system   kube-apiserver-master                 1/1     Running   0          12h
kube-system   kube-controller-manager-master        1/1     Running   0          12h
kube-system   kube-flannel-ds-hb8rp                 1/1     Running   0          12h
kube-system   kube-flannel-ds-windows-amd64-sg7cg   1/1     Running   0          12h
kube-system   kube-proxy-mbv76                      1/1     Running   0          12h
kube-system   kube-proxy-windows-l9fld              1/1     Running   0          12h
kube-system   kube-scheduler-master                 1/1     Running   0          12h
```
