### ISSUE TITLE
Once 1.21 is fixed we should be able to revert to defaults for kubeproxy

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/sig-windows-tools#148]
Revert the PR #147 

given this is a breaking change in kube-proxy we should be fixing it in a 1.21 patch release?
to me it seems we should wait for that, instead of toggling off the feature gate.

_Originally posted by @neolit123 in https://github.com/kubernetes-sigs/sig-windows-tools/issues/147#issuecomment-818270182_

**Comment by neolit123** [comment]
/remove lifecycle-stale

i see https://github.com/kubernetes/kubernetes/pull/101047 merged recently.
