### ISSUE TITLE
KubeCluster.ps1 errors with $Global:InterfaceName doesn't exist

### ISSUE THREAD

**Issue by sathishc58** [kubernetes-sigs/sig-windows-tools#156]
I am trying to add  Windows Server 2019 as a node to my existing K8S Cluster (runs on CentOS 7)  by following this URL

[https://v1-17.docs.kubernetes.io/docs/setup/production-environment/windows/user-guide-windows-nodes/](url)

I download the sig-windows-tools and executed `'KubeCluster.ps1'` but it failed with the following error 

```
PS C:\Kubernetes\sig-windows-tools\kubeadm> .\KubeCluster.ps1 -ConfigFile .\v1.15.0\Kubeclustervxlan.json -install
[DownloadFile] File C:\Kubernetes\sig-windows-tools\kubeadm\hns.psm1 already exists.
WARNING: The names of some imported commands from the module 'hns' include unapproved verbs that might make them less
discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose
parameter. For a list of approved verbs, type Get-Verb.
Ethernet doesn't exist
At C:\Kubernetes\sig-windows-tools\kubeadm\KubeClusterHelper.psm1:135 char:9
+         throw "$Global:InterfaceName doesn't exist"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Ethernet doesn't exist:String) [], RuntimeException
    + FullyQualifiedErrorId : Ethernet doesn't exist

```
Output of Get-NetAdapter

```
PS C:\Kubernetes\sig-windows-tools\kubeadm> Get-NetAdapter

Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
Ethernet0                 Intel(R) 82574L Gigabit Network Conn...      11 Up           00-50-56-B8-C9-A0         1 Gbps
vEthernet (nat)           Hyper-V Virtual Ethernet Adapter             18 Up           00-15-5D-10-9C-B1        10 Gbps
```

**Expected behavior**
KubeCluster.ps1 script should be able to configure Windows

**Kubernetes (please complete the following information):**
 - Windows Server version:  2019
 - Kubernetes Version:
 - CNI:

**Additional context**

**Comment by neolit123** [comment]
this logic is failing for you:
https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/kubeadm/KubeClusterHelper.psm1#L124-L132

try using this function to print the loaded config:
https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/kubeadm/KubeClusterHelper.psm1#L157

**Comment by neolit123** [comment]
> https://v1-17.docs.kubernetes.io/docs/setup/production-environment/windows/user-guide-windows-nodes/

also this documentation might be out of date, compared to what this repository has.
try 1.19+

**Comment by jsturtevant** [comment]
Please try the newer docs, but in this case it looks like you might have the wrong value for the Adapter Name. Looks like `Ethernet` instead of `Ethernet0`.

**Comment by sathishc58** [comment]
> Please try the newer docs, but in this case it looks like you might have the wrong value for the Adapter Name. Looks like `Ethernet` instead of `Ethernet0`.

Yes you are correct.  I updated the value from `Ethernet` to `Ethernet0` in `KubeCluster.ps1` file which resolved the issue.  Thank you for pointing it out
