### ISSUE TITLE
Development support for image-builder

### ISSUE THREAD

**Issue by knabben** [kubernetes-sigs/sig-windows-tools#169]
**Is your feature request related to a problem? Please describe.**
In order support the 'sig-windows-dev-tools`  repository and speed up the host bootstrap, we need a ready to-go Kubernetes node created preferably with image-builder using the same scripts as production for development boxes.

**Describe the solution you'd like**
This proposal is to start a few scripts to configure a image-builder target aiming in specifically in virtualbox, these are the steps required to change the image and allow a final user create in an easy way a new development Windows node from zero.

An initial vbox image PR is already open here:
https://github.com/kubernetes-sigs/image-builder/pull/699

These are the high level steps required to change the target via custom ansible roles:

1. Create a `vagrant` user with a pub key installed on authorized_keys
2. Set IP address and required network interfaces
2. Force containerd as runtime
3. Reconfigure Kubelet
3. Install a CNI with different options (antrea/calico)

**Describe alternatives you've considered**

**Comment by knabben** [comment]
cc @FriedrichWilken @perithompson

**Comment by jayunit100** [comment]
talkd to amim, moving to dev-tools since its really specific to that and sig-win-tools is bloated w other things
