### ISSUE TITLE
Add a script for adding shutdown hooks for CNIs

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/sig-windows-tools#177]
**Is your feature request related to a problem? Please describe.**
Some CNIs might want to run some shutdown hooks on reboot, which is common after say, windows updates on a kubelet.

**Describe the solution you'd like** 
A script that we can curl and then use, say in image-builder, that registers pre shutdown hooks.

**Comment by marosset** [comment]
@jayunit100 / @hxietkg did https://github.com/kubernetes-sigs/sig-windows-tools/pull/178 fully address this issue?
