### ISSUE TITLE
Pods can't be killed normally after Node restart

### ISSUE THREAD

**Issue by vitaliy-leschenko** [kubernetes-sigs/sig-windows-tools#184]
**Describe the bug**
Command `kubectl delete pods/%podname%` stucks on deleting pods.
When I try to describe the pods, I see the message:
```
Events:
  Type     Reason          Age               From               Message
  ----     ------          ----              ----               -------
  Normal   Scheduled       17m               default-scheduler  Successfully assigned default/demo-85d57c4449-f5wgk to k8s-windows-2
  Normal   Pulling         17m               kubelet            Pulling image "mcr.microsoft.com/windows/nanoserver:ltsc2022"
  Normal   Pulled          15m               kubelet            Successfully pulled image "mcr.microsoft.com/windows/nanoserver:ltsc2022" in 1m30.8318989s
  Normal   Created         15m               kubelet            Created container demo-server
  Normal   Started         15m               kubelet            Started container demo-server
  Normal   SandboxChanged  3m36s             kubelet            Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          3m32s             kubelet            Container image "mcr.microsoft.com/windows/nanoserver:ltsc2022" already present on machine
  Normal   Created         3m32s             kubelet            Created container demo-server
  Normal   Started         3m30s             kubelet            Started container demo-server
  Normal   Killing         68s               kubelet            Stopping container demo-server
  Warning  FailedKillPod   3s (x8 over 68s)  kubelet            error killing pod: failed to "KillPodSandbox" for "4723efd3-cb10-4c0c-8b45-c8f7ab981155" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to remove network namespace for sandbox \"d8be8cd9b8acfb344ddd598358e8464fc9580121c576af2410235594d4210d89\": hcnDeleteNamespace failed in Win32: The specified request is unsupported. (0x803b0015) {\"Success\":false,\"Error\":\"The specified request is unsupported. \",\"ErrorCode\":2151350293}"
```

**To Reproduce**
1. Deploy new k8s cluster with CRI contaierD and CNI Calico
2. Deploy any pod on windows node
3. Try to delete the pod on windows node

**Expected behavior**
Pods delete without any events.

**Kubernetes (please complete the following information):**
 - Windows Server version: 2022
 - Kubernetes Version: 1.22.2
 - CNI: Calico
 - CRI: containerD 1.6.0.beta-1

**Comment by jsturtevant** [comment]
do you know what caused the `  Normal   SandboxChanged  3m36s             kubelet            Pod sandbox changed, it will be killed and re-created.`?  

I don't see this on 2019 or 2022 clusters.  We may need kubelet/containerd logs to see if anything else is wrong for that pod

**Comment by vitaliy-leschenko** [comment]
Sometimes pods start without network interface after node restart. Maybe when calico is not initialized yet.
After remove pods with --force they creating again, working well and can be removed without any problem.

So, maybe pods can't be deleted because network interface doesn't exists for the pods.

**Comment by vitaliy-leschenko** [comment]
I confirm that this issue reproduced after node restart without drain/cordon/uncordon.
The same situation might be after node power fail.

**Comment by jsturtevant** [comment]
Thanks could you give explicit reproduction steps?  Do you have a mitigation?

**Comment by claudiubelu** [comment]
> 
> 
> Sometimes pods start without network interface after node restart. Maybe when calico is not initialized yet. After remove pods with --force they creating again, working well and can be removed without any problem.
> 
> So, maybe pods can't be deleted because network interface doesn't exists for the pods.

Interesting. According to [1], this error occurs on ``sandbox.NetNS.Remove()``, which is after ``c.teardownPodNetwork(ctx, sandbox)``. Going further down, we can see that it's probably not because the Network Namespace is missing, we'd have succeeded in that case. I can say that I haven't encountered this issue when the Pod's namespace is missing when I was trying out [3].

This could use some investigation, and I wonder if this issue can be reproduced without a node restart. That would help making it easier to reproduce, and make it easier to create a test against this issue.

[1]: https://github.com/containerd/containerd/blob/195def141fc15181d5d837b92aa9462a12a0e809/pkg/cri/server/sandbox_stop.go#L93
[2]: https://github.com/containerd/containerd/blob/195def141fc15181d5d837b92aa9462a12a0e809/pkg/netns/netns_windows.go#L56
[3]: https://github.com/containerd/containerd/pull/6180

**Comment by vitaliy-leschenko** [comment]
> This could use some investigation, and I wonder if this issue can be reproduced without a node restart. That would help making it easier to reproduce, and make it easier to create a test against this issue.

Unfortunately, I don't know how to reproduce it without node restart. But the issue reproduces after every node restart if some pods was running before on the node.

**Comment by jsturtevant** [comment]
In other implementations with kubelet we have delete all containers, cleaned up all networks, etc. I was hoping this wasn't necessary.  Maybe we can root cause this issue and solve it fully otherwise we can try that approach

**Comment by vitaliy-leschenko** [comment]
> Thanks could you give explicit reproduction steps? Do you have a mitigation?

1. setup k8s with 1+ windows nodes
2. run windows pods on the node
3. restart windows node
4. await a few seconds after node restarted and pods increase restarts count.
5. connect to the pod and run `ipconfig`
6. the pod doesn't have any network interfaces but k8s think that it exists because `kubectl get pods` shows ip.

**Comment by vitaliy-leschenko** [comment]
when you delete broken pods with `--force` key it restarts (because it's part of deployment for example) and works fine.

**Comment by vitaliy-leschenko** [comment]
It looks like calico issue. I have tried to deploy k8s cluster with calico using official calico manual. It has the same issue.

**Comment by jsturtevant** [comment]
Is there an issue opened in calico?

**Comment by vitaliy-leschenko** [comment]
@jsturtevant Yes, it is. I opened the same issue in calico repo.

**Comment by jsturtevant** [comment]
Thank you for cross linking!

**Comment by jsturtevant** [comment]
going to leave this closed in favor of https://github.com/projectcalico/calico/issues/5828
