### ISSUE TITLE
Can't exec command in HostProcess pods with -it keys

### ISSUE THREAD

**Issue by vitaliy-leschenko** [kubernetes-sigs/sig-windows-tools#185]
**Describe the bug**
Can't exec command in HostProcess pods with -it keys

**To Reproduce**
Deploy k8s 1.22.* with cri-containerd 1.6.0+ and hostprocess pods (kube-proxy for example)
```
PS C:\Users\v.leschenko> kubectl -n kube-system exec -it kube-proxy-windows-9p7xm -- cmd
error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "a4ead75c4424e7476f3b5f0b47b2c1421aa489e1977a2a661414adfac6807047": console emulation not supported for job containers: unknown
```

**Expected behavior**
Can exec command with -it keys.

**Kubernetes (please complete the following information):**
 - Windows Server version: 2022
 - Kubernetes Version: 1.22.2
 - CNI: Calico
 - CRI: containerD 1.6.0 beta 1

**Comment by marosset** [comment]
Unfortunately TTY support does not currently work for HostProcess containers.
You should be able to exec in w/ -i (but things like tab completion will not work).
We hope to have this addressed before moving the feature to stable.

**Comment by jsturtevant** [comment]
This support will go into hcsshim so I created an issue there for tracking the work: https://github.com/microsoft/hcsshim/issues/1221
