### ISSUE TITLE
Join the window node network problem

### ISSUE THREAD

**Issue by sczhh** [kubernetes-sigs/sig-windows-tools#186]
Please help to see what caused it, and is there any solution?

" kube-flannel-ds-windows-amd64"  logs:
`FATA[2021-11-08T21:55:32-08:00] rpc error: code = Internal desc = could not create IP forward entry: The object already exists. `

"kube-proxy-windows" Event:
`(combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "c0e340c5a911b4351183e570af0d9cdd57b96f3711bff823074f7f16fe1cfb8d" network for pod "kube-proxy-windows-qgkjt": networkPlugin cni failed to set up pod "kube-proxy-windows-qgkjt_kube-system" network: error while GETHNSNewtorkByName(flannel.4096): Network flannel.4096 not found`

**Comment by jsturtevant** [comment]
looks like your Flannel pod may not have set up the network properly.  Is there more to the flannel logs you could share?

**Comment by jsturtevant** [comment]
haven't heard back. open another issue if still having trouble.
/close
