### ISSUE TITLE
docs sharding for super easy to update windows Recipes

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/sig-windows-tools#217]
We need a more easy to use and easy to update, less beuracratic, windows-centric way to install and maintain windows nodes, w recipes for people to quickly borrow and use. 

- minimize the windows docs in kubernetes.io that arent foundational... i.e. things involving CNIs, external tools, PS1 scripts, and so on
- Add a doc page for all the real world windows use cases
  - windows-image builder
  - Windows CSI drivers 
  - Windows CSI-proxy intro and installation 
  - NSSM, how to use and inspect it
  - Example of using containerd on windows kubelets
  - windows CNI 
    - w antrea -> symlinked to dev tools
    - w calico -> symlinked to official calico docs or dev tools
  - Intro to windows w/ sig-win-dev-tools
  - Intro to windows clusters w/ CAPZ
  - Intro to windows using GKE
  - Intro to windows using EKS
  - Intro to windows using AKS
  - Intro to host-process recipes 
    - sym link to calico docs
    - sym link to sig-win-dev-tools for antrea EXPERIMENTS/ doc (maybe zac or amim makes it)
  - GMSA walkthrough and introduction (xinqi ?)  

As part of this lets add some recipes to sig-windows dev tools on

- how calico woks and is installed
- how antrea works and is installed

**Comment by jayunit100** [comment]
this needs an owner, sig win folks (me, mark, amim, claudio ) can pair with the owner on helping w technical content

**Comment by knabben** [comment]
As someone mentioned in the call - +1 for the idea of using the CAPI standard project for this: https://rust-lang.github.io/mdBook/

**Comment by marosset** [comment]
www.kubernetes.io discourages providing documentation (including setup) for third party content.
This means that setup instructions for various things like contianerd, individual CNIs, etc or any solutions that require other tools (like NSSM) are generally rejected.
Unfortunately a lot of the Windows solutions require extra tools or advanced configuration.

In an ideal world each project would be updated to fully document how things work on Windows as well as they do for linux.
While we work towards achieving that goal SIG-Windows leadership feels it is important to provide that documentation _someplace_ for the benefit of users and the best location we came up with was this repository.

**Comment by jsturtevant** [comment]
There are several unofficial guides that could be used as reference: 

https://github.com/kubernetes-sigs/sig-windows-tools/issues/128#issuecomment-1135605935
https://github.com/kubernetes-sigs/sig-windows-tools/issues/128#issuecomment-1068271427
https://github.com/kubernetes-sigs/sig-windows-tools/issues/128#issuecomment-1172470841
https://github.com/kubernetes-sigs/sig-windows-tools/issues/128#issuecomment-1172585274

**Comment by lippertmarkus** [comment]
As we already have some content in https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=containerd#windows-server-1 may this would be a suitible place?

**Comment by jsturtevant** [comment]
/remove-lifecycle rotten
 /remove-lifecycle stale

being worked on #239

**Comment by profnandaa** [comment]
> this needs an owner, sig win folks (me, mark, amim, claudio ) can pair with the owner on helping w technical content

I can take this up, but will need some guidance on the best approach; as per the discussion with James here #255
