### ISSUE TITLE
hosts file used by another  process

### ISSUE THREAD

**Issue by Fareroo7** [kubernetes-sigs/sig-windows-tools#222]
**Describe the bug**
When I try to run the Add-Content command I get the following error:

```
Add-Content : The process cannot access the file 'C:\Windows\System32\drivers\etc\hosts' 
because it is being used by another process.
At line:1 char:1
+ Add-Content -Path C:\Windows\System32\drivers\etc\hosts -Value "127.0 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Windows\System32\drivers\etc\hosts:String) [A 
   dd-Content], IOException
    + FullyQualifiedErrorId : GetContentWriterIOError,Microsoft.PowerShell.Commands.AddCont 
   entCommand
```

**To Reproduce**
start any windows container and run this command in powershell:
`Add-Content -Path 'c:\windows\system32\drivers\etc\hosts' -Value "127.0.0.1 $env:computername"`

**Expected behavior**
being able to modify the hosts file

**Kubernetes (please complete the following information):**
 - Windows Server version: 2019 (BuildNr 17763.2928)
 - Kubernetes Version: 1.24.0
 - CNI: 0.2.0 flannel in container with hostprocess

**Comment by lippertmarkus** [comment]
I think that's intended behavior. You can add additional host entries with `hostAliases`: https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/#adding-additional-entries-with-hostaliases

**Comment by marosset** [comment]
I believe this is intended behavior too.

Here is the PR that adds `hostAliases` support for windows - https://github.com/kubernetes/kubernetes/pull/83730
I do see that if there is a /etc/hosts is already being mounted into the container then the kubelet should not try and build a hosts file for the pod
https://github.com/claudiubelu/kubernetes/blob/de4602995b0fc44037b0cc826c2bde61b4bb21a2/pkg/kubelet/kubelet_pods.go#L137-L144
@claudiubelu might have some insights too

**Comment by Fareroo7** [comment]
That makes sense, of course...
I removed the command from my startup script and added `hostAliases` to my deployment YAML and everything is working.
Thanks a lot! 😄
