### ISSUE TITLE
kubeproxy flannel hostprocess 1.23 specifies removed feature gate IPv6DualStack 

### ISSUE THREAD

**Issue by jonaskello** [kubernetes-sigs/sig-windows-tools#223]
When upgrading kubeproxy hostprocess from 1.22 to 1.23 we got this error:

```
E0525 15:42:54.394374   19404 run.go:74] "command failed" err="failed complete: cannot set feature gate IPv6DualStack to false, feature is locked to true"
```

It seems this line sets `IPv6DualStack ` to false:

https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/hostprocess/flannel/kube-proxy/start.ps1#L64

However this feature gate seems to be completely removed in 1.23:

https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

I guess it should be removed from start.ps1 too?

**Comment by Parkhost** [comment]
Yes, already made a PR:

-  #225

**Comment by Parkhost** [comment]
you may close this issue as the PR got merged 👍🏻
