### ISSUE TITLE
stop using the cluster admin.conf for "flannel --kubeconfig"

### ISSUE THREAD

**Issue by neolit123** [kubernetes-sigs/sig-windows-tools#23]
when workers are joining the cluster we use the admin.conf the "kubeadm init" created and the user copied under "~/.kube".

https://github.com/kubernetes-sigs/sig-windows-tools/blob/78f258a7eda6f06d417733b75a087c61998e15f7/kubeadm/KubeClusterHelper.psm1#L24-L29

giving workers admin rights is a security risk.
in my opinion we cannot graduate the kubeadm/windows feature to beta, unless this is resolved.

flannel does not require full blown admin rights to operate and according to @benmoss the privileges that it needs are here:
https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml#L49-L76

a potential solution here once the control-plane is started using "kubeadm init" the command "kubeadm alpha kubeconfig user ..." can be used to generate a new scoped kubeconfig for a group (ORG) that only has priviliges for this cluster-role https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml#L49-L76
this possibly means applying a new clusterrolebinding too.

/area security
/kind design
/priority important-longterm
cc @michmike

**Comment by neolit123** [comment]
if @benmoss ' workaround for using deamonsets goes live, this is no longer needed:
https://github.com/benmoss/kubeadm-windows

**Comment by benmoss** [comment]
As part of the move to the new kubeadm on Windows approach with 1.18 we are closing issues related to the previous alpha.

/close
