### ISSUE TITLE
support "kubeadm upgrade" on Windows worker nodes

### ISSUE THREAD

**Issue by neolit123** [kubernetes-sigs/sig-windows-tools#24]
requirement for beta graduation.

/assign
/kind feature
/priority important-longterm

**Comment by neolit123** [comment]
i did experimentation for this feature and it works fine.

here was my process:

Linux node:
- download kubelet and kubeadm v1.16.x
- create a 1.16.x Linux control-plane node using "kubeadm init"

Windows node:
- run the kubelet 
- join the Windows node "kubeadm join" and the token the Linux node generated
- start kube-proxy.exe
- start flanneld.exe in "host-gw" mode

make sure the cluster nodes are ready and using "v1.16.x"

Linux node:
- upgrade kubeadm  to v1.17.0
- call "kubeadm upgrade apply v1.17.0"
- upgrade the kubelet to v1.17.0 and restart it

Windows node:
- download kubeadm v1.17.0
- run "kubeadm upgrade node"
- stop the kubelet
- download and start kubelet v1.17.0

make sure the cluster node are ready and using v1.17.0

my problem at this point is that i don't have the expertise to write powershell.
i think using poweshell is a good choice in terms of the tight integration of the OS, but not a good choice in terms of how many people can contribute to this code.

the `upgrade.cmd` in Windows Batch looks in the lines of:

```
@echo off
:: target version to upgrade to
set UPGRADE_VER=v1.17.0

:: download the kubeadm binary
curl.exe -Lo "C:\k\kubeadm.exe" https://dl.k8s.io/%UPGRADE_VER%/bin/windows/amd64/kubeadm.exe

:: run kubeadm upgrade
C:\k\kubeadm upgrade node

:: stop the kubelet, download a new version and start it again
powershell Stop-Service kubelet
curl.exe -Lo "C:\k\kubelet.exe" https://dl.k8s.io/%UPGRADE_VER%/bin/windows/amd64/kubelet.exe
powershell Start-Service kubelet
```

i will try to translate this to primitive powershell and send a PR, but don't expect much of my skills there.

cc @benmoss @michmike @PatrickLang

**Comment by michmike** [comment]
@benmoss, is this something you have accounted for in this release cycle?

**Comment by neolit123** [comment]
with the changes that merged from @benmoss . upgrades do not really need extra scripts and the steps can be just documented.

/close
