### ISSUE TITLE
Create flannel image for Windows Server 2022

### ISSUE THREAD

**Issue by Mik4sa** [kubernetes-sigs/sig-windows-tools#251]
In addition to #237 please create a new git tag so we can use the official images.
When I added the support 2022 months back with #205 I assumed that the images get created/updated soon.

I'm going to need the images in some weeks again and I would like to use the official ones.

PS: Is it possible that you update the v0.13.0 too?

@vitaliy-leschenko Is this something you can do?

**Comment by luxzeitlos** [comment]
What is the status here?

**Comment by marosset** [comment]
Let me remove the Windows SAC references since those are out of support and I then I can start a release / git tag / etc

**Comment by Mik4sa** [comment]
@marosset Isn't this done and can be closed :)?

**Comment by marosset** [comment]
yup!

/close
