### ISSUE TITLE
Pods don't have internet access (Flannel vxlan)

### ISSUE THREAD

**Issue by meilel** [kubernetes-sigs/sig-windows-tools#252]
**Describe the bug**
I am running into a problem with my Windows Nodes on a 1.25.4 Cluster. Pods running on windows nodes don't have internet access, they are also no accessible from other pods.
However the pods are running and i can exec into them.
I have an flannel vxlan overlay network configured with the following net-conf and I use containerd as CRI.
```{
  "Network": "10.245.0.0/16",
  "Backend": {
    "Type": "vxlan",
    "VNI" : 4096,
    "Port": 4789
  }
}
```
The Flannel pod log shows an error, but i am not sure if this is related.
```
WARNING: The names of some imported commands from the module 'hns' include unapproved verbs that might make them less
discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose
parameter. For a list of approved verbs, type Get-Verb.
Invoke-HnsRequest : @{Error=An adapter was not found. ; ErrorCode=2151350278; Success=False}
At C:\k\flannel\hns.psm1:233 char:16
+ ...      return Invoke-HnsRequest -Method POST -Type networks -Data $Json ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-HNSRequest
```
I can see who has 10.0.175.115? Tell 172.28.147.180 requests on the vEthernet (nat) Interface with Wireshark. The 10.0.175.115 is the IP of the Windows Server, while the 172.28.147.180 is the Pod-IP.

On Linux container everything works as expected.

**Kubernetes (please complete the following information):**
 - Windows Server version: 2019 
 - Kubernetes Version: 1.25.4
 - CRI: containerd://1.4.1
 - CNI: Flannel

**Comment by fabi200123** [comment]
The default Network for flannel is `10.244.0.0/16` and if you want to update it to `10.245.0.0/16` make sure to update it in all yaml files that are going to be applied.

**Comment by claudiubelu** [comment]
Flannel pod log? You mean you're running flannel as a host process container? You've mentioned that you're using containerd 1.4.1, which is very old. According to the documentation, you need containerd 1.6+ for Host Process Containers, since that's when the feature was introduced. https://kubernetes.io/docs/tasks/configure-pod-container/create-hostprocess-pod/#limitations
