### ISSUE TITLE
flannel hostprocess: incompatible CNI versions; config is "0.3.1", plugin supports ["0.2.0"]

### ISSUE THREAD

**Issue by Mik4sa** [kubernetes-sigs/sig-windows-tools#266]
**Describe the bug**
Following [this guide](https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/guides/guide-for-adding-windows-node.md) for Kubernetes 1.26.0 results into the following error for flannel:
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "8249f8c9d4845a1cfda66c0bc5becd7d035d3250c63a79e283a7352a3c8d6156": plugin type="flannel" name="flannel.4096" failed (add): incompatible CNI versions; config is "0.3.1", plugin supports ["0.2.0"]
```

Note: This issue assumes the changes from #265 (to fix #264). This problem was noted there already.

**To Reproduce**
Just follow the guide to add a (new) windows node: https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/guides/guide-for-adding-windows-node.md while using the fix from #265

**Expected behavior**
Flannel should start without any erros.

**Kubernetes (please complete the following information):**
 - Windows Server version: Windows Server 2022 (21H2, Build 20348.1366)
 - Kubernetes Version: 1.26.0
 - CNI: flannel

**Comment by Mik4sa** [comment]
While creating this issue @fabi200123 already answered this problem in #264:
> I might know how to fix this... It might be because of something I tried to fix and missmatched the files that I commited. I will look over it soon. Also, the solution will be to change [here ](https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/hostprocess/flannel/flanneld/flannel-overlay.yml#L14) from 0.3.1 to 0.2.0 and reapply the flannel yaml. Let me know if that fixes it for you

Thanks for that :)
I'm going to try the change you mentioned.

Lets focus this error in this issue.

**Comment by Mik4sa** [comment]
@fabi200123 The change you mentioned works. Thanks :)

**Comment by shivangbhar** [comment]
@Mik4sa As per the latest commit in master, is it expected to install cni plugin on worker nodes explicitly now? Since that part is removed from Install-Containerd.ps1?

**Comment by Mik4sa** [comment]
As far as I understood this is no longer needed and the flannel hostprocess pod sets this up for you. All I did was following the guide mentioned above with the changes from my three last pull requests. I "installed" nothing else on my Windows Server 2022 node
Hope this helps you :)

**Comment by shivangbhar** [comment]
I am still seeing errors in my flannel pod regarding the cni path :(. May be the containerd installation is diff for our setups. Did you use the latest Install-Containerd.ps1 for containerd installation?

**Comment by Mik4sa** [comment]
Yes. I used the latest commit, for sure.
Do you really use the right yaml files from my pull request and not the one from master? Both, the one for flannel and for kube-proxy, were changed

**Comment by Mik4sa** [comment]
@shivangbhar All my PR's got merged. You now should be able to follow the guide as it is on master :)
