### ISSUE TITLE
Auto-detect Windows version and use matching containers

### ISSUE THREAD

**Issue by kellybirr** [kubernetes-sigs/sig-windows-tools#27]
Windows server containers need to be version matched to the host OS version when using the default "process" isolation.  It would be more convenient if "KubeCluster.ps1" would check the windows version and automatically use the matching tag for the "Pause", "NanoServer" and "ServerCore" containers. This would be less error prone for new users than the current method of specifying in a config file.

I propose making these settings in the JSON split between container id and tag, for each, with the tag empty by default.  When the tag is empty, the script would automatically determine based `[System.Environment]::OSVersion.Version` and use the appropriate version.

I'm happy to put in the work and submit a PR.  I just want to make sure this would be useful to more than just myself and a welcome addition before doing it.

Thoughts?

**Comment by PatrickLang** [comment]
I think this makes sense, would welcome a PR. We do need to keep these available if someone wants to override them in a config though. Windows Server Insider builds are a bit harder to deal with and usually need some manual paths chosen.

KubeCluster.ps1 has a section that fills in defaults that are missing. That's probably the best place to put it. It will then write it to a config file so all parameters can be persisted across reboots or reviewed later.

**Comment by PatrickLang** [comment]
Here's a similar logic https://github.com/Azure/aks-engine/blob/7ab155567b279d4fad2fc39e50447b1ccfdc8261/parts/k8s/windowskubeletfunc.ps1#L149

**Comment by kellybirr** [comment]
Perfect... I actually had to roll my own "pause" container in my cluster build this week.  There isn't currently one for 19.03 or 19.09.  That link gives me a good example to start from.  I'll work on it over the next couple weeks as I have time, while traveling.

**Comment by kellybirr** [comment]
Still looking at this, just moving slowly. I will get a PR in if we can keep the issue open a while longer. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
