### ISSUE TITLE
kubeadm script PrepareNode.ps1: Remove requirement on git being installed

### ISSUE THREAD

**Issue by jonaskello** [kubernetes-sigs/sig-windows-tools#278]
The `PrepareNode.ps1` script now seems to require git to be installed. For example on this line:

https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/kubeadm/scripts/PrepareNode.ps1#L113

This complicates the setup a lot since it is not easy to get git installed on Windows Server 2022 and also not easy to get it working in Powershell. Especially in an scripted automated way.

If possible, I would suggest to rework the parts of the script that require git to be installed so it does not need git.

**Comment by jsturtevant** [comment]
Agree shouldn't need that dependency.  Would you be able open a PR?
