### ISSUE TITLE
KubeCluster.ps1 should ensure Docker service is running.

### ISSUE THREAD

**Issue by kellybirr** [kubernetes-sigs/sig-windows-tools#28]
Twice, if forgotten to check that the docker service was actually started before executing "Kubecluster.ps1 ... -join".  This causes the script to fail and you have to exit PS and restart before you can run it again.

I propose adding `Start-Service Docker` to the `-join` script to ensure the service is running before proceeding.  

It may also be good to add `Set-Service -Name Docker -StartupType Automatic` to `-install`.  For some reason the Docker installation does not always set this properly.

**Comment by kellybirr** [comment]
As with my other recommendation.  I'm happy to do the work and submit a PR.  I just wanted to start with an issue and get community feedback.

**Comment by PatrickLang** [comment]
sure, improvements are always welcome! One thing that would be helpful though is to make sure it's in a section that's checking `$Global:ClusterConfiguration.Cri.Name` since I'm working on ContainerD installation steps for these scripts https://github.com/kubernetes-sigs/sig-windows-tools/compare/master...PatrickLang:kubeadm-containerd (work in progress, not complete yet)

**Comment by kellybirr** [comment]
That's a great point.  I sometimes forget that Kubernetes works with container frameworks other than Docker.  Don't want the code to make bad assumptions.  I'll review your branch and start from there.

**Comment by a4099181** [comment]
Please see #17. Docker is now registered as a dependency for kubelet service.

**Comment by kellybirr** [comment]
@PatrickLang, looking at your WiP, I think that something as simple as adding 
`WaitForServiceRunningState -ServiceName $depends -TimeoutSeconds 30`
in `InstallKubelet` between where your `$depends = switch ($Global:Cri) {` statement and the `New-Service -Name "kubelet"` statement (~ line 938), would ensure that the dependecy is either running or will start, before installing Kubelet.  This is really probably not completely necessary, given the registration of Kubelet with the dependency, but it will make troubleshooting a bit easier for someone with a Docker (or Containerd) issue.

I think it's probably safe to close this issue.  I hate to put in a PR that would conflict with your WiP and would really only be 1-2 line(s) of code.
