### ISSUE TITLE
Installation of crictl missing in InstallContainerd.ps1 script

### ISSUE THREAD

**Issue by jonaskello** [kubernetes-sigs/sig-windows-tools#281]
**Describe the bug**
When joining a windows worker installed with scripts
- [Install-Containerd.ps1](https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/kubeadm/scripts/Install-Containerd.ps1)

You will get this error message when running `kubeadm join`:

```[preflight] Running pre-flight checks
W0120 15:42:35.881614    4636 checks.go:1021] [preflight] WARNING: Couldn't create the interface used for talking to the container runtime: crictl is required by the container runtime: exec: "crictl": executable file not found in %PATH%
```

**Expected behavior**
To have all prerequistes for `kubeadm join` installed by the scripts.

**Kubernetes (please complete the following information):**
 - Windows Server version: 2022
 - Kubernetes Version: 1.24.9
 - CNI: Flannel

**Comment by jonaskello** [comment]
In order to make it work you need to install crictl like this:

```ps1

$crictl_version="1.24.1"

# Install crictl from the cri-tools project which is required so that kubeadm can talk to the CRI endpoint.
curl.exe -LO https://github.com/kubernetes-sigs/cri-tools/releases/download/v$crictl_version/crictl-v$crictl_version-windows-amd64.tar.gz
tar xvf crictl-v$crictl_version-windows-amd64.tar.gz
mv crictl.exe "$global:ConainterDPath"

# Configure crictl
mkdir -Force "$home\.crictl"
@"
runtime-endpoint: npipe://./pipe/containerd-containerd
image-endpoint: npipe://./pipe/containerd-containerd
timeout: 10
#debug: true
"@ | Set-Content "$home\.crictl\crictl.yaml" -Force
crictl.exe info
```

I think perhaps this could be added to the script InstallContainerd.ps1 ?

**Comment by jsturtevant** [comment]
we can added it to the script.  It isn't strictly necessary for a functional cluster which is why it is a warning message.  I am not sure what installing it would enable to be honest.  It's always been on my list but never got around to it, if you could help figure out what it's used for that would be helpful!

**Comment by Mik4sa** [comment]
> I am not sure what installing it would enable to be honest. [...] if you could help figure out what it's used for that would be helpful!

When for example resetting a node with `kubeadm.exe reset` I get the following warning:
```
W0527 13:38:37.600183    6996 cleanupnode.go:99] [reset] Failed to remove containers: crictl is required by the container runtime: executable file not found in %PATH%
```

So it looks like it's used atleast for some cleanup tasks.

Is this enough for you to add `crictl` to the install script?

**Comment by jsturtevant** [comment]
works for me
