### ISSUE TITLE
PermissionDenied: (C:\hpc\etc\kube-flannel\net-conf.json:FileInfo) [Copy-Item], UnauthorizedAccessException

### ISSUE THREAD

**Issue by grader75** [kubernetes-sigs/sig-windows-tools#289]
I think you need to know this https://github.com/flannel-io/flannel/issues/1758

**Comment by Mik4sa** [comment]
While updating some components yesterday I stumbled about the same error but didn't gave it much attention though and ignored it.
I'm a bit unsure what you did here to solve this. Can you explain more or open a pull request for it?

**Comment by Mik4sa** [comment]
Somehow this is a thing with containerD 1.7.0. It's reproducible. This error isn't happening with containerD 1.6.20.
