### ISSUE TITLE
KubeCluster.ps1 : Item has already been added. Key in dictionary 'Kube'

### ISSUE THREAD

**Issue by guidjome** [kubernetes-sigs/sig-windows-tools#29]
Hello,

I have an issue when i launch the KubeCluster.ps1. I've the error message bellow. I don't understand what is the key mentionned by the error message.

Can you help me ?

> Unable to connect to the control-plane node. Reason [Item has already been added. Key in dictionary: 'Kube'  Key being added: 'Kube']
At D:\sig-windows-tools-master\kubeadm\KubeCluster.ps1:311 char:9
>+         throw "Unable to connect to the control-plane node. Reason [$ ...
>+         >~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>    + CategoryInfo          : OperationStopped: (Unable to conne... added: 'Kube']:String) [], >RuntimeException
>    + FullyQualifiedErrorId : Unable to connect to the control-plane node. Reason [Item has already >been added. Key in dictionary: 'Kube'  Key being added: 'Kube']

**Comment by adelina-t** [comment]
So, it is possible you have been running the script multiple times? Meaning, you ran it once, hit an error, ran it again and got this?
The error, I think originates here: https://github.com/kubernetes-sigs/sig-windows-tools/blob/1113abc0c516311f3bb650f9907f4a71f9f08141/kubeadm/KubeClusterHelper.psm1#L1195

It tries to set something in $Global:Configuration, but the item already exists. The script should be fixed to check for this, but either way, what you can do in the meantime, is before you rerun the script, set $Global:Configuration = @{}

**Comment by benmoss** [comment]
Yeah, I was hitting this same issue and just did `$Global:Configuration.Remove("Kube")`

**Comment by benmoss** [comment]
As part of the move to the new kubeadm on Windows approach with 1.18 we are closing issues related to the previous alpha.
/close
