### ISSUE TITLE
Hyper-V Windows features still necessary?

### ISSUE THREAD

**Issue by Mik4sa** [kubernetes-sigs/sig-windows-tools#296]
**Is your feature request related to a problem? Please describe.**
Yesterday I wanted to create a new cluster for testing purposes on some new VPS I bought. The Linux part went straightforward without any errors and all ports were starting successfully. On the other hand I got an error while installing the required windows feature "Hyper-V" (from `Install-Containerd.ps1` script) on my windows node. It said that my machine/CPU doesn't support that. Since this isn't my machine I couldn't fix that.
Also I was always wondering why Hyper-V was necessary to install a container runtime. So I simply removed the "Hyper-V" and "Hyper-V-PowerShell" features from `Install-Containerd.ps1` and tried it anyway. And it works (so far). The flannel pods are running successfully on my windows machine.
Additionally I deployed the webserver described here https://kubernetes.io/docs/concepts/windows/user-guide/#getting-started-deploying-a-windows-container and even that is working. I could even reach the pod from outside (via node port).

**Describe the solution you'd like**
Remove the windows features "Hyper-V" and "Hyper-V-PowerShell" from the `Install-Containerd.ps1` script, so that they're not installed and no virtualization features are necessary.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by jsturtevant** [comment]
There is a long thread on this topic at: https://kubernetes.slack.com/archives/C0SJ4AFB7/p1607619445072100

To summarize:
- Hyper-v is not strictly necessary to run Process isolated containers
- _But_ Hyper-v is required for the VM switch commandlets which are sometimes required as a pre-requisite for CNI's to set up the networks properly (ususaly creating a network before the cni is executed to avoid network drops and other issues).  See workaround (https://github.com/kubernetes-sigs/image-builder/blob/3c9c5642ac78be02ff631a19fef6fc3dab4c1a90/images/capi/ansible/windows/roles/systemprep/tasks/main.yml#L157-L176)
- hyper-v support in containerd via cri is now in 1.7 (https://github.com/containerd/containerd/issues/6862)

Given all that, I don't think we want to remove it completely but could make it configurable.

**Comment by Mik4sa** [comment]
Ah that's interesting to know. Thanks :)
I think the documentation should atleast mention this so that those machines can use Kubernetes anyway
