### ISSUE TITLE
calico-node-windows-XXXXX CrashLoopBackOff

### ISSUE THREAD

**Issue by Sameer-Italiya** [kubernetes-sigs/sig-windows-tools#302]
Hi everyone, I want to create a hybrid cluster (1 Master ( ubuntu 18.04 ) and 1 Worker ( windows server 2019 )). At the end of this installation, I want to run a Windows container and access my web app by NodePort service.

**Kubernetes details**:

Windows Server version: 1809 (OS Build 17763.4252)
Kubernetes Version: 1.24.13
CNI: Calico hostprocess

**Describe the error**
While creating a win-webserver pod in Windows the status of the container is in ContainerCreating and calico-node-windows-xxxxx pod status change to CrashLoopBackOff. Below are the logs of both pods

-> kubectl logs calico-node-windows-cftdd -n kube-system

2023-05-08 12:13:06.247 [ERROR][8032] startup/startup.go 111: Unable to ensure datastore is migrated. error=unable to query ClusterInformation to determine Calico version: connection is unauthorized: clusterinformations.crd.projectcalico.org "default" is forbidden: User "system:serviceaccount:kube-system:calico-node" cannot get resource "clusterinformations" in API group "crd.projectcalico.org" at the cluster scope

-> kubectl describe pod win-webserver-6cd44bf97-2x8x9

Events:
  Type    Reason          Age                        From     Message
  ----    ------          ----                       ----     -------
  Normal  SandboxChanged  4m33s (x24334 over 3d16h)  kubelet  Pod sandbox changed, it will be killed and re-created.

**Expected behavior**
All containers should be run

**Comment by claudiubelu** [comment]
Hello. At a first glance, it looks like some RBAC issues. Have you applied the rbac yaml described in step 4 in this Calico hostprocess guide? https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/guides/guide-for-adding-windows-node.md#configuring-calico-hostprocess

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/sig-windows-tools/master/hostprocess/calico/kube-calico-rbac.yml
```

**Comment by Sameer-Italiya** [comment]
I have already completed step 4 as per documentation and its looks like after rebooting the server these RBAC changes are removed and one more time run step 4 and below is the output of the command

serviceaccount/calico-node unchanged
clusterrole.rbac.authorization.k8s.io/calico-node configured
clusterrolebinding.rbac.authorization.k8s.io/calico-node configured

After reapplying the setting still the same issue comes and one more thing to notice is that if we try to remove the win-webserver pod then it's in terminate state only and not removed and below are the logs

win-webserver log
===========
Events:
  Type     Reason                  Age                  From               Message
  ----     ------                  ----                 ----               -------
  Normal   Scheduled               3m49s                default-scheduler  Successfully assigned default/win-webserver-6cd44bf97-lbf9j to mttestiskub04
  Warning  FailedCreatePodSandBox  3m48s                kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "70af7121771cae0d587375e2cebb97b18620d42da2bd997a7da6f21fe507e27f": plugin type="calico" failed (add): error getting ClusterInformation: connection is unauthorized: clusterinformations.crd.projectcalico.org "default" is forbidden: User "system:serviceaccount:kube-system:calico-node" cannot get resource "clusterinformations" in API group "crd.projectcalico.org" at the cluster scope
  Normal   SandboxChanged          0s (x19 over 3m47s)  kubelet            Pod sandbox changed, it will be killed and re-created.

calico-node-windows-xxxxx
==================
2023-05-08 14:59:44.071 [ERROR][6280] startup/startup.go 111: Unable to ensure datastore is migrated. error=unable to query ClusterInformation to determine Calico version: connection is unauthorized: clusterinformations.crd.projectcalico.org "default" is forbidden: User "system:serviceaccount:kube-system:calico-node" cannot get resource "clusterinformations" in API group "crd.projectcalico.org" at the cluster scope

**Comment by claudiubelu** [comment]
> I have already completed step 4 as per documentation and its looks like after rebooting the server these RBAC changes are removed and one more time run step 4 and below is the output of the command
> 
> serviceaccount/calico-node unchanged clusterrole.rbac.authorization.k8s.io/calico-node configured clusterrolebinding.rbac.authorization.k8s.io/calico-node configured
> 

That is a bit strange, I wonder who / what updated those RBACs? Do you have anything else running in that K8s environment, or some system like a CD that updates the resources in kubernetes for you? And does this happen only when you reboot the control plane node?

> After reapplying the setting still the same issue comes and one more thing to notice is that if we try to remove the win-webserver pod then it's in terminate state only and not removed and below are the logs
> # win-webserver log
> 
> Events: Type Reason Age From Message
> 
> Normal Scheduled 3m49s default-scheduler Successfully assigned default/win-webserver-6cd44bf97-lbf9j to mttestiskub04 Warning FailedCreatePodSandBox 3m48s kubelet Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "70af7121771cae0d587375e2cebb97b18620d42da2bd997a7da6f21fe507e27f": plugin type="calico" failed (add): error getting ClusterInformation: connection is unauthorized: clusterinformations.crd.projectcalico.org "default" is forbidden: User "system:serviceaccount:kube-system:calico-node" cannot get resource "clusterinformations" in API group "crd.projectcalico.org" at the cluster scope Normal SandboxChanged 0s (x19 over 3m47s) kubelet Pod sandbox changed, it will be killed and re-created.

That might be because there's no CNI. Typically, when deleting a Pod, its CNI endpoint also has to be deleted, but since there's no CNI, it gets stuck on that part (this could also have happened if you had an active CNI, the Pod became ``Running``, and then the CNI went down). I'm not sure it could assume it doesn't have any CNI endpoint without having a CNI it can use.

> # calico-node-windows-xxxxx
> 
> 2023-05-08 14:59:44.071 [ERROR][6280] startup/startup.go 111: Unable to ensure datastore is migrated. error=unable to query ClusterInformation to determine Calico version: connection is unauthorized: clusterinformations.crd.projectcalico.org "default" is forbidden: User "system:serviceaccount:kube-system:calico-node" cannot get resource "clusterinformations" in API group "crd.projectcalico.org" at the cluster scope

Well, if somehow the RBAC changes you've applied kept reverting, it could still lead to this error.

There are a couple bits of information which might be useful:

- are you using containerd 1.6 or newer on Windows? You can check by checking the k8s nodes, or by running ``C:\Program Files\containerd\containerd.exe --version`` or something similar on the Windows node. Host process containers are only supported on containerd 1.6 or newer: https://v1-24.docs.kubernetes.io/docs/tasks/configure-pod-container/create-hostprocess-pod/#limitations
- what Calico version are you using (calico-node daemonsets on both Linux and Windows)? The Calico version is also set in the image's tag, if you're using the images detailed in the guide.
- I wonder if the RBAC yaml should look different on Kubernetes 1.24? Probably not, but it might be worth investigating.

**Comment by Sameer-Italiya** [comment]
This is the only testing environment and nothing else there. One thing to notice is that it is not related reboot issue but the same command RBAC runs after something then it will change the output.

**containerd version**
C:\Program Files\containerd>containerd.exe --version
containerd github.com/containerd/containerd v1.6.20 2806fc1057397dbaeefbea0e4e17bddfbd388f38

**calico version hostprocess**
ubuntu master node = v3.25.0
windows worker node = v3.25.0

**Comment by fabi200123** [comment]
Tried to reproduce this one with:

- Linux: k8s 1.24.13, containerd 1.7.0
- Windows: k8s 1.24.13, containerd 1.6.20
- Calico version v3.25.0

I ended up with a working cluster with CNI, but when I try to add a new pod, I get this error:
`Warning  FailedCreatePodSandBox  10s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "aa57bc8e718456b3aa51304671c81f93978589373ac89958ebb61a532ccf56ea": plugin type="calico" failed (add): error creating calico client: host must be a URL or a host:port pair: "https://"
  Normal   Scheduled               10s   default-scheduler  Successfully assigned default/iis-8c9f8c6f8-kmv4p to win-kjq4utr64p6
  Normal   SandboxChanged          9s    kubelet            Pod sandbox changed, it will be killed and re-created.
` and the pod gets stuck in `ContainerCreating` status.

**Comment by jsturtevant** [comment]
@Sameer-Italiya can you share the contents of the following roles?  It seems like one of them isn't configured properly to access 

```
serviceaccount/calico-node
clusterrole.rbac.authorization.k8s.io/calico-node
clusterrolebinding.rbac.authorization.k8s.io/calico-node
```

**Comment by SanjayGuntur** [comment]
I've experimenting with adding a windows node since the last few days and hit both issues mentioned in the ticket.

Cluster Info:
```
K8SVERSION   OS-IMAGE                         KERNEL-VERSION    CONTAINER-RUNTIME
v1.28.2      Debian GNU/Linux 12 (bookworm)   6.1.0-13-amd64    containerd://1.7.7
v1.28.2      Windows Server 2022 Datacenter   10.0.20348.1970   containerd://1.7.7

Calico: v3.26.1
```
After following all the steps in the guide, both nodes reported ready, and everything looked neat and tidy. When I tried to deploy a sample app, hit the first problem.

- Pod creation failed with ` host must be a URL or a host:port pair: "https://"`
  - Possible fix: The value of server in c:\etc\cni\net.d\calico-kubeconfig had only `https://` (no control plane ip/port). This [line](https://github.com/kubernetes-sigs/sig-windows-tools/blob/e35b2e1622f3039a70956d4173faaceb067bc613/hostprocess/calico/install/calico-install.ps1#L16C4-L16C4) seems to expect the configmap to contain the controlplaneEndpoint, but it does not. The controlplane endpoint could be sourced from other config files already available on the node?
- After fixing the config file manually, I hit the next issue. `User "system:serviceaccount:kube-system:calico-node" cannot get resource "clusterinformations" in API group "crd.projectcalico.org"`
  - Possible fix: After running the script to deploy calico on linux nodes, I noticed that the service account `calico-node` in ns `calico-system`, cluster role `calico-node` and a clusterrolebiniding between them was already created. when following the instructions and running the [rbac manifest](https://github.com/kubernetes-sigs/sig-windows-tools/blob/e35b2e1622f3039a70956d4173faaceb067bc613/hostprocess/calico/kube-calico-rbac.yml#L82C1-L82C1), it creates service account `calico-node` in ns kube-system, updates the cluster role `calico-node` (although no rules changed from the earlier defintion) and updates the clusterrolebinding (removing `calico-system:calico-node` as subject, and adding `kube-system:calico-node`). I edited the rbac manifest and create only the `calico-node` service account in ns kube-system and a clusterrolebinding (with name `calico-node-win`) to existing clusterrole `calico-node` (without any changes to the clusterrole itself). Still don't understand why the error mentioned the service account in kube-system ns though.

At this point, I was able to deploy the sample app without any problems. I don't understand all the moving parts. Happy to follow up with a PR, if I get any guidance or advice.

**Comment by mloskot** [comment]
## Works for me

I have just build the two-node hybrid cluster on Hyper-V VM-s running on Windows 11 host:
- Ubuntu Server 22.04
- Windows Server 2022

following these two guides on the Windows node part:
- https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/guides/guide-for-adding-windows-node.md
- https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/guides/calico.md

with the following components:
- Kubernetes 1.29.0
- ContainerD 1.7.11
- Calico 3.27.0 on Linux master node
- Calico 3.26.1 on Windows worker master node, but only because latest images are not yet available, see
   - https://github.com/kubernetes-sigs/sig-windows-tools/issues/353

and I did not experience any Calico issues.
   
![image](https://github.com/kubernetes-sigs/sig-windows-tools/assets/80741/d1da894b-d65c-4910-aa59-76cf1570d0f3)

![image](https://github.com/kubernetes-sigs/sig-windows-tools/assets/80741/016890c1-f2b9-4c71-b324-c2afcefdf784)

```
$ kubectl -n kube-system describe pod calico-node-windows-85sks
Name:             calico-node-windows-85sks
Namespace:        kube-system
Priority:         0
Service Account:  calico-node
Node:             vm-winworker/192.168.0.3
Start Time:       Wed, 20 Dec 2023 20:25:53 +0000
Labels:           app=calico
                  controller-revision-hash=5d667bdb46
                  pod-template-generation=1
                  tier=node
Annotations:      <none>
Status:           Running
IP:               192.168.0.3
IPs:
  IP:           192.168.0.3
Controlled By:  DaemonSet/calico-node-windows
Init Containers:
  install-cni:
    Container ID:  containerd://0447cba46a427b6b9b39771ef4835f3ce802d5c3a6a06004538ac097915b1d21
    Image:         sigwindowstools/calico-install:v3.26.1-hostprocess
    Image ID:      docker.io/sigwindowstools/calico-install@sha256:e21aa2036dee9ae6b4a4e5f916d5832be43fe3c97ae06b697dd0ec478661ff29
    Port:          <none>
    Host Port:     <none>
    Args:
      $env:CONTAINER_SANDBOX_MOUNT_POINT/calico/install.ps1
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 20 Dec 2023 20:26:13 +0000
      Finished:     Wed, 20 Dec 2023 20:26:13 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      CNI_CONF_NAME:         10-calico.conflist
      CNI_NETWORK_CONFIG:    <set to the key 'cni_network_config' of config map 'calico-config-windows'>  Optional: false
      KUBERNETES_NODE_NAME:   (v1:spec.nodeName)
      CNI_MTU:               <set to the key 'veth_mtu' of config map 'calico-config-windows'>  Optional: false
      SLEEP:                 false
      K8S_SERVICE_CIDR:      10.96.0.0/12
      CNI_BIN_DIR:           c:\opt\cni\bin
      CNI_CONF_DIR:          c:\etc\cni\net.d
    Mounts:
      /etc/kubeadm-config/ from kubeadm-config (rw)
      /host/etc/cni/net.d from cni-net-dir (rw)
      /host/opt/cni/bin from cni-bin-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-vdtb2 (ro)
Containers:
  calico-node-startup:
    Container ID:  containerd://2d8c5407c0fdcc50a3bee98c538dab54f3d41bcf951b0af7677394b40d7eef09
    Image:         sigwindowstools/calico-node:v3.26.1-hostprocess
    Image ID:      docker.io/sigwindowstools/calico-node@sha256:faeac084cc2955990f4d9c005c9e2299296d8ada6fe87338db761db11b6e91db
    Port:          <none>
    Host Port:     <none>
    Args:
      $env:CONTAINER_SANDBOX_MOUNT_POINT/calico/node-service.ps1
    State:          Running
      Started:      Wed, 20 Dec 2023 20:26:36 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      POD_NAME:                   calico-node-windows-85sks (v1:metadata.name)
      POD_NAMESPACE:              kube-system (v1:metadata.namespace)
      CNI_IPAM_TYPE:              calico-ipam
      CALICO_NETWORKING_BACKEND:  vxlan
      KUBECONFIG:                 C:/etc/cni/net.d/calico-kubeconfig
      VXLAN_VNI:                  4096
    Mounts:
      /etc/kube-calico-windows/ from calico-config-windows (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-vdtb2 (ro)
  calico-node-felix:
    Container ID:  containerd://00fdd985022abd4112c4239139393f55c0ffc3d6869b635e655f3d5061c3568f
    Image:         sigwindowstools/calico-node:v3.26.1-hostprocess
    Image ID:      docker.io/sigwindowstools/calico-node@sha256:faeac084cc2955990f4d9c005c9e2299296d8ada6fe87338db761db11b6e91db
    Port:          <none>
    Host Port:     <none>
    Args:
      $env:CONTAINER_SANDBOX_MOUNT_POINT/calico/felix-service.ps1
    State:          Running
      Started:      Wed, 20 Dec 2023 20:26:38 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      POD_NAME:       calico-node-windows-85sks (v1:metadata.name)
      POD_NAMESPACE:  kube-system (v1:metadata.namespace)
      VXLAN_VNI:      4096
      KUBECONFIG:     C:/etc/cni/net.d/calico-kubeconfig
    Mounts:
      /etc/kube-calico-windows/ from calico-config-windows (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-vdtb2 (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True
  Initialized                 True
  Ready                       True
  ContainersReady             True
  PodScheduled                True
Volumes:
  calico-config-windows:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      calico-config-windows
    Optional:  false
  cni-bin-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/cni/bin
    HostPathType:
  cni-net-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/cni/net.d
    HostPathType:
  kubeadm-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kubeadm-config
    Optional:  false
  kube-api-access-vdtb2:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 :NoSchedule op=Exists
                             :NoExecute op=Exists
                             CriticalAddonsOnly op=Exists
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  47m   default-scheduler  Successfully assigned kube-system/calico-node-windows-85sks to vm-winworker
  Normal  Pulling    47m   kubelet            Pulling image "sigwindowstools/calico-install:v3.26.1-hostprocess"
  Normal  Pulled     47m   kubelet            Successfully pulled image "sigwindowstools/calico-install:v3.26.1-hostprocess" in 18.109s (18.109s including waiting)
  Normal  Created    47m   kubelet            Created container install-cni
  Normal  Started    47m   kubelet            Started container install-cni
  Normal  Pulling    46m   kubelet            Pulling image "sigwindowstools/calico-node:v3.26.1-hostprocess"
  Normal  Pulled     46m   kubelet            Successfully pulled image "sigwindowstools/calico-node:v3.26.1-hostprocess" in 17.804s (17.804s including waiting)
  Normal  Created    46m   kubelet            Created container calico-node-startup
  Normal  Started    46m   kubelet            Started container calico-node-startup
  Normal  Pulling    46m   kubelet            Pulling image "sigwindowstools/calico-node:v3.26.1-hostprocess"
  Normal  Pulled     46m   kubelet            Successfully pulled image "sigwindowstools/calico-node:v3.26.1-hostprocess" in 1.582s (1.582s including waiting)
  Normal  Created    46m   kubelet            Created container calico-node-felix
  Normal  Started    46m   kubelet            Started container calico-node-felix
```

**Comment by SanjayGuntur** [comment]
@mloskot, This is from my notes from earlier experiments, just sharing...

```
export CALICO_VERSION="v3.26.1"

# Deploy kube-proxy and calico daemonsets. Note calico.yaml and kube-calico-rabc.yml might throw warnings.
curl -L https://raw.githubusercontent.com/kubernetes-sigs/sig-windows-tools/master/hostprocess/calico/kube-proxy/kube-proxy.yml | sed 's/KUBE_PROXY_VERSION/v1.28.2/g' | kubectl apply -f -
curl -L https://raw.githubusercontent.com/kubernetes-sigs/sig-windows-tools/master/hostprocess/calico/calico.yml | sed "s/CALICO_VERSION/$CALICO_VERSION/g" | kubectl apply -f -
 
#This manifest breaks the windows node with rbac permissions. What follows is a workaround until the manifest is fixed.
#kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/sig-windows-tools/master/hostprocess/calico/kube-calico-rbac.yml
 
kubectl apply -f - <<EOF
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-node
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: calico-node-win
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-node
subjects:
  - kind: ServiceAccount
    name: calico-node
    namespace: kube-system
EOF
```

**Comment by danijam** [comment]
Hey both, good timing to see this being discussed as we were facing the above issues. Thanks @SanjayGuntur for the workaround above. That seemed to get us past that problem. 

However... are you guys seeing your calico-node actually start running? 
`kubectl get pods --all-namespaces -o wide`
```
NAMESPACE          NAME                                       READY   STATUS        RESTARTS        AGE   IP               NODE         NOMINATED NODE   READINESS GATES
calico-apiserver   calico-apiserver-668cf8647d-7wnfw          1/1     Running       0               17m   192.168.179.84   ubuntu2304   <none>           <none>
calico-apiserver   calico-apiserver-668cf8647d-84hnd          1/1     Running       0               17m   192.168.179.81   ubuntu2304   <none>           <none>
calico-system      calico-kube-controllers-54486fcf5d-srp9w   1/1     Running       0               17m   192.168.179.82   ubuntu2304   <none>           <none>
calico-system      calico-node-7wbkl                          0/1     Running       0               17m   192.168.99.2     ubuntu2304   <none>           <none>
calico-system      calico-typha-9969fcb65-knr75               1/1     Running       0               17m   192.168.99.2     ubuntu2304   <none>           <none>
calico-system      csi-node-driver-7zs2p                      2/2     Running       0               17m   192.168.179.88   ubuntu2304   <none>           <none>
default            nginx-deployment-65d54bf6f9-hw7fz          1/1     Running       0               17m   192.168.179.83   ubuntu2304   <none>           <none>
default            nginx-deployment-65d54bf6f9-zbpkz          1/1     Running       0               17m   192.168.179.85   ubuntu2304   <none>           <none>
default            sample-568d69d7d8-fskkw                    1/1     Running       0               17m   192.168.55.69    winnode      <none>           <none>
kube-system        calico-node-windows-qg9zc                  2/2     Running       1 (6m43s ago)   17m   192.168.99.3     winnode      <none>           <none>
kube-system        coredns-5dd5756b68-gf64f                   1/1     Running       0               17m   192.168.179.87   ubuntu2304   <none>           <none>
kube-system        coredns-5dd5756b68-tvfxq                   1/1     Running       0               17m   192.168.179.86   ubuntu2304   <none>           <none>
kube-system        etcd-ubuntu2304                            1/1     Running       1 (27m ago)     17m   192.168.99.2     ubuntu2304   <none>           <none>
kube-system        kube-apiserver-ubuntu2304                  1/1     Running       1 (27m ago)     17m   192.168.99.2     ubuntu2304   <none>           <none>
kube-system        kube-controller-manager-ubuntu2304         1/1     Running       2 (26m ago)     17m   192.168.99.2     ubuntu2304   <none>           <none>
kube-system        kube-proxy-jdfxx                           1/1     Running       0               17m   192.168.99.2     ubuntu2304   <none>           <none>
kube-system        kube-proxy-windows-zhfwt                   1/1     Running       0               17m   192.168.99.3     winnode      <none>           <none>
kube-system        kube-scheduler-ubuntu2304                  1/1     Running       1 (27m ago)     17m   192.168.99.2     ubuntu2304   <none>           <none>
tigera-operator    tigera-operator-94d7f7696-wmnwc            1/1     Running       0               17m   192.168.99.2     ubuntu2304   <none>           <none>
```
pod `calico-node-7wbkl` is 0/1. `kubectl describe` gives us

```
Warning  Unhealthy  4m2s (x96 over 17m)  kubelet  (combined from similar events): Readiness probe failed: 2023-12-22 15:33:31.114 [INFO][1786] confd/health.go 180: Number of node(s) with BGP peering established = 0
calico/node is not ready: BIRD is not ready: BGP not established with 192.168.99.3
```
Seems like the BGP network is not working. The virtual network these nodes are on has full connectivity. It's just a local hyper-v switch network and the Windows node and Linux node don't have their firewalls turned on so I don't think this is blocked connectivity... Are you seeing this?

**Comment by SanjayGuntur** [comment]
@danijam, I don't see any issues with the networking. This is the same cluster I was experimenting a few months back. I haven't worked with it since then.

```
NAMESPACE          NAME                                       READY   STATUS    RESTARTS       AGE   IP               NODE         NOMINATED NODE   READINESS GATES
calico-apiserver   calico-apiserver-56598bbdbb-pjd7w          1/1     Running   10 (13m ago)   61d   10.244.205.70    k8s-mst-01   <none>           <none>
calico-apiserver   calico-apiserver-56598bbdbb-wqj4r          1/1     Running   10 (13m ago)   61d   10.244.205.69    k8s-mst-01   <none>           <none>
calico-system      calico-kube-controllers-66c8797d9d-5f255   1/1     Running   10 (13m ago)   61d   10.244.205.127   k8s-mst-01   <none>           <none>
calico-system      calico-node-dtxv2                          1/1     Running   10 (13m ago)   61d   192.168.8.3      k8s-mst-01   <none>           <none>
calico-system      calico-typha-7b6c9bb466-cr74h              1/1     Running   18 (12m ago)   61d   192.168.8.3      k8s-mst-01   <none>           <none>
calico-system      csi-node-driver-28w5p                      2/2     Running   20 (13m ago)   61d   10.244.205.65    k8s-mst-01   <none>           <none>
kube-system        calico-node-windows-frlmp                  2/2     Running   6 (7d7h ago)   60d   192.168.8.4      k8s-win-01   <none>           <none>
kube-system        coredns-5dd5756b68-d6999                   1/1     Running   10 (13m ago)   61d   10.244.205.126   k8s-mst-01   <none>           <none>
kube-system        coredns-5dd5756b68-p5gcd                   1/1     Running   10 (13m ago)   61d   10.244.205.125   k8s-mst-01   <none>           <none>
kube-system        etcd-k8s-mst-01                            1/1     Running   10 (13m ago)   61d   192.168.8.3      k8s-mst-01   <none>           <none>
kube-system        kube-apiserver-k8s-mst-01                  1/1     Running   10 (13m ago)   61d   192.168.8.3      k8s-mst-01   <none>           <none>
kube-system        kube-controller-manager-k8s-mst-01         1/1     Running   16 (12m ago)   61d   192.168.8.3      k8s-mst-01   <none>           <none>
kube-system        kube-proxy-4shxj                           1/1     Running   10 (13m ago)   61d   192.168.8.3      k8s-mst-01   <none>           <none>
kube-system        kube-proxy-windows-v44sb                   1/1     Running   3 (7d7h ago)   60d   192.168.8.4      k8s-win-01   <none>           <none>
kube-system        kube-scheduler-k8s-mst-01                  1/1     Running   10 (13m ago)   61d   192.168.8.3      k8s-mst-01   <none>           <none>
tigera-operator    tigera-operator-94d7f7696-jzkkf            1/1     Running   19 (13m ago)   61d   192.168.8.3      k8s-mst-01   <none>           <none>
```

**Comment by mloskot** [comment]
Thanks @SanjayGuntur for the hints in https://github.com/kubernetes-sigs/sig-windows-tools/issues/302#issuecomment-1866298999 I've started re-building my cluster but still no luck. I can not get Calico 3.26.1 working. I must be doing something wrong as apparently I can not even get the step 3. `watch kubectl get pods -n calico-system` from https://docs.tigera.io/calico/latest/getting-started/kubernetes/quickstart#install-calico complete. So, I will give it few more attempts before I post any more details. Yes, @danijam, you did spot the problem on my end and, as I explained, I need to review my procedure.

By the way there is similar discussion in 
- https://github.com/kubernetes-sigs/sig-windows-tools/issues/293#issuecomment-1708135768

**Comment by SanjayGuntur** [comment]
@mloskot, I updated the  `calico-kubeconfig` manually. I haven't investigated if I can source the control plane endpoint from anywhere else, It was scratch experiment, so I boxed only a few days to see what it takes to get a hybrid cluster working. I'll see if i can rebuild the cluster again with the scripts I have.

**Comment by mloskot** [comment]
@SanjayGuntur Thank you for the update. I created my hybrid Kubernetes 1.29 cluster on Hyper-V VM-s from scratch, because previously I made a few  _very rookie mistakes_ 😊 

First, I did not pass pod CIDR to `kubeadm init`. Since my nodes live in network 192.168.0.0/24, it led to [clashing overlap with Calico default pod CIDR `192.168.0.0/16`](https://sabrnet.wzk.cz/2021/08/kubernetes-pod-network-cidr-and-service-cidr-cant-overlap-with-intranet-network-ranges/).  So, I fixed it on my end as follows:

  ```
  kubeadm init --pod-network-cidr=10.85.0.0/24 --service-cidr=10.85.10.0/16
  ```

Next, I followed with Calico 3.26.1 installation on my master node and eventually got, I think, all Calico nodes up and running:

```console
mloskot@master:~$ kubectl get pod -A
NAMESPACE          NAME                                       READY   STATUS    RESTARTS   AGE
calico-apiserver   calico-apiserver-647f755948-8sclm          1/1     Running   0          2m33s
calico-apiserver   calico-apiserver-647f755948-lq9wp          1/1     Running   0          2m33s
calico-system      calico-kube-controllers-5fff76c8f7-b2sfh   1/1     Running   0          4m57s
calico-system      calico-node-rk5sc                          1/1     Running   0          4m57s
calico-system      calico-typha-6fbd5b6d79-jldnw              1/1     Running   0          4m57s
calico-system      csi-node-driver-b4dms                      2/2     Running   0          4m57s
kube-system        coredns-76f75df574-79c8l                   1/1     Running   0          38m
kube-system        coredns-76f75df574-wttnp                   0/1     Running   0          38m
kube-system        etcd-master                                1/1     Running   0          38m
kube-system        kube-apiserver-master                      1/1     Running   0          38m
kube-system        kube-controller-manager-master             1/1     Running   0          38m
kube-system        kube-proxy-cd6gb                           1/1     Running   0          38m
kube-system        kube-scheduler-master                      1/1     Running   0          38m
tigera-operator    tigera-operator-94d7f7696-96slg            1/1     Running   0          7m54s
```

Finally, I joined my Windows Server 2022 node and installed Calico according to your https://github.com/kubernetes-sigs/sig-windows-tools/issues/302#issuecomment-1866298999 with corrected RBAC:

```console
mloskot@master:~$ k get pods -A -o wide
NAMESPACE          NAME                                       READY   STATUS    RESTARTS   AGE     IP            NODE        NOMINATED NODE   READINESS GATES
calico-apiserver   calico-apiserver-647f755948-8sclm          1/1     Running   0          3h7m    10.85.0.5     master      <none>           <none>
calico-apiserver   calico-apiserver-647f755948-lq9wp          1/1     Running   0          3h7m    10.85.0.6     master      <none>           <none>
calico-system      calico-kube-controllers-5fff76c8f7-b2sfh   1/1     Running   0          3h9m    10.85.0.4     master      <none>           <none>
calico-system      calico-node-rk5sc                          1/1     Running   0          3h9m    192.168.0.2   master      <none>           <none>
calico-system      calico-typha-6fbd5b6d79-jldnw              1/1     Running   0          3h9m    192.168.0.2   master      <none>           <none>
calico-system      csi-node-driver-b4dms                      2/2     Running   0          3h9m    10.85.0.3     master      <none>           <none>
kube-system        calico-node-windows-gjzdl                  2/2     Running   0          7m10s   192.168.0.4   winworker   <none>           <none>
kube-system        coredns-76f75df574-79c8l                   1/1     Running   0          3h42m   10.85.0.2     master      <none>           <none>
kube-system        coredns-76f75df574-wttnp                   0/1     Running   0          3h42m   10.85.0.1     master      <none>           <none>
kube-system        etcd-master                                1/1     Running   0          3h43m   192.168.0.2   master      <none>           <none>
kube-system        kube-apiserver-master                      1/1     Running   0          3h43m   192.168.0.2   master      <none>           <none>
kube-system        kube-controller-manager-master             1/1     Running   0          3h43m   192.168.0.2   master      <none>           <none>
kube-system        kube-proxy-cd6gb                           1/1     Running   0          3h42m   192.168.0.2   master      <none>           <none>
kube-system        kube-proxy-windows-rc8pv                   1/1     Running   0          8m25s   192.168.0.4   winworker   <none>           <none>
kube-system        kube-scheduler-master                      1/1     Running   0          3h43m   192.168.0.2   master      <none>           <none>
tigera-operator    tigera-operator-94d7f7696-96slg            1/1     Running   0          3h12m   192.168.0.2   master      <none>           <none>
```

Now, I think, I can answer @danijam question from https://github.com/kubernetes-sigs/sig-windows-tools/issues/302#issuecomment-1867826322 with confirmation I got my Calico nodes running and they seem to run without any restarts :-)

**Comment by SanjayGuntur** [comment]
@mloskot, Happy to see you have a running cluster. You may hit the issue with the incomplete server url in `C:\etc\cni\net.d\calico-kubeconfig` only when deploying a windows pod.

**Comment by danijam** [comment]
When it get back round to it I need to try the new v3.27 of Calico, as I understand it is enabling a better windows node bootstrapping process? https://github.com/projectcalico/calico/blob/release-v3.27/release-notes/v3.27.0-release-notes.md

**Comment by mloskot** [comment]
@danijam Yes, see also https://github.com/kubernetes-sigs/sig-windows-tools/issues/353#issuecomment-1874450778
