### ISSUE TITLE
Push new images to docker hub

### ISSUE THREAD

**Issue by Mik4sa** [kubernetes-sigs/sig-windows-tools#317]
**Describe the bug**
The images, atleast for flannel and kube-proxy, are outdated (see https://github.com/kubernetes-sigs/sig-windows-tools/pull/308#issuecomment-1551110003 and #316). We should push a new version to docker hub.

Also I feel like we should add an action to automatically push new Versions. Do you agree?

**Comment by jonaskello** [comment]
I'm also looking for new flannel images but cannot find any.

Is the workaround to build them yourself for now?

**Comment by Mik4sa** [comment]
See https://github.com/kubernetes-sigs/sig-windows-tools/issues/336#issuecomment-1633854019

> To build your own images prepare a docker installation powered by linux containers on a windows system. Execute this command to create the builder needed to build flannel and kube-proxy:
> ```
> docker buildx create --name img-builder --use --platform windows/amd64
> ```
> 
> Afterwars clone this repo and checkout the master branch. Open this folder in a terminal `/hostprocess/flannel/flanneld`.
> Set `$flannelVersion` and `$repository` accordingly. I used for example `$flannelVersion="v0.21.5"` and `$repository="mik4sa"`. Last but not least execute this command to build and push your image:
> ```
> docker buildx build --provenance=false --sbom=false --platform windows/amd64 --output=type=registry --pull --build-arg=flannelVersion=$flannelVersion -f Dockerfile -t $repository/flannel:$flannelVersion-hostprocess .
> ```
> 
> Next open this folder in a terminal `/hostprocess/flannel/kube-proxy`.
> Set `$proxyVersion` and `$repository` accordingly. I used for example `$proxyVersion="v1.27.1"` and `$repository="mik4sa"`. Last but not least execute this command to build and push your image:
> ```
> docker buildx build --provenance=false --sbom=false --platform windows/amd64 --output=type=registry --pull --build-arg=k8sVersion=$proxyVersion -f Dockerfile -t $repository/kube-proxy:$proxyVersion-flannel-hostprocess .
> ```
> 
> In the manifest you apply, so `flannel-overlay.yml` and `kube-proxy.yml` you need to reference the image you just created. So change `image: sigwindowstools/[...]` to `image: mik4sa/[...]`
