### ISSUE TITLE
Kube-Flannel-Windows pod Imagepull error and crashloopbackoff error

### ISSUE THREAD

**Issue by milanankush** [kubernetes-sigs/sig-windows-tools#319]
There seems to be no image on dockerhub corresponding to the image pulled in when the flannel-overlay file is applied on v0.21.5-flannel-hostprocess. It would be helpful if you can give me some docker registry having the appropriate image that I can pull locally and make a personal repo out of it.

**Comment by milanankush** [comment]
@Mik4sa please look into this issue once

**Comment by Mik4sa** [comment]
You can easily build one for yourself. Check [hostprocess/flannel/build.sh](hostprocess/flannel/build.sh).

For example execute these commands from `hostprocess/flannel/flanneld` directory:
```
docker buildx create --name img-builder --use --platform windows/amd64
docker buildx build --provenance=false --sbom=false --platform windows/amd64 --output=type=registry --pull --build-arg=flannelVersion=$flannelVersion -f Dockerfile -t $repository/flannel:$flannelVersion-hostprocess .
```

Set `$flannelVersion` and `$repository` as you need them.

Note: The first command needs to be executed only once.

**Comment by milanankush** [comment]
> You can easily build one for yourself. Check https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/hostprocess/flannel/build.sh.
> 
> For example execute these commands from `hostprocess/flannel/flanneld` directory:
> 
> ```
> docker buildx create --name img-builder --use --platform windows/amd64
> docker buildx build --provenance=false --sbom=false --platform windows/amd64 --output=type=registry --pull --build-arg=flannelVersion=$flannelVersion -f Dockerfile -t $repository/flannel:$flannelVersion-hostprocess .
> ```
> 
> Set `$flannelVersion` and `$repository` as you need them.
> 
> Note: The first command needs to be executed only once.

@Mik4sa  I'm getting the following error while doing so :-

[+] Building 2.9s (1/1) FINISHED
 => ERROR [internal] booting buildkit                                                                              2.9s
 => => pulling image moby/buildkit:buildx-stable-1                                                                 2.9s
 => => creating container buildx_buildkit_img-builder0                                                             0.0s
------
 > [internal] booting buildkit:
------
ERROR: Error response from daemon: Windows does not support privileged mode

and there is no image for flannel-hostprocess v0.21.5 on sigwindows/flannel dockerhub registery

**Comment by milanankush** [comment]
@Mik4sa could you give me similar steps for kube-proxy flannel hostprocess also?

**Comment by Mik4sa** [comment]
> @Mik4sa could you give me similar steps for kube-proxy flannel hostprocess also?

https://github.com/kubernetes-sigs/sig-windows-tools/blob/d744f5488dd350fa967b3920d698b268e214e14d/hostprocess/flannel/build.sh#LL36C3-L36C222

**Comment by Mik4sa** [comment]
@milanankush Does everything work now for you? If so can you close this issue then?

**Comment by arp-mbender** [comment]
Quite frankly, while it is true that it's relatively easy to build this, one then has to set up and push this to a registry. It'd be much more helpful if these images were made available from the docker sigwindowstools registry. In other words - it would be nice if one could follow the guides as written, rather than hit errors and then be told "build it yourself"...

**Comment by Mik4sa** [comment]
I just tried it again. I'm on a Windows 11 machine, running the docker desktop version `4.32.0 (157355)` in linux mode and running the two commands from above (in PowerShell Core v7.4.3).
The two needed variables are assigned as follows:
`$flannelVersion="v0.21.5"`
`$repository="mik4sa"`
