### ISSUE TITLE
Which sandbox (pause) image to use

### ISSUE THREAD

**Issue by Mik4sa** [kubernetes-sigs/sig-windows-tools#323]
In this [kubernetes guide](https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd) to configure `containerd` as the CRI runtime there is the following section:
> #### Overriding the sandbox (pause) image
>
> In your [containerd config](https://github.com/containerd/containerd/blob/main/docs/cri/config.md) you can overwrite the sandbox image by setting the following config:
>
> ```toml
> [plugins."io.containerd.grpc.v1.cri"]
>   sandbox_image = "registry.k8s.io/pause:3.2"
> ```
>
> You might need to restart `containerd` as well once you've updated the config file: `systemctl restart containerd`.
>
> Please note, that it is a best practice for kubelet to declare the matching `pod-infra-container-image`.
If not configured, kubelet may attempt to garbage collect the `pause` image.
There is ongoing work in [containerd to pin the pause image](https://github.com/containerd/containerd/issues/6352)
and not require this setting on kubelet any longer.

Currently our [guide](https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/guides/guide-for-adding-windows-node.md) has no such section to inform about this. As far as I could see by just following the guide (as I did) we end with two different configured images.
For containerD 1.7.1 the default configuration uses `registry.k8s.io/pause:3.8`
In our `PrepareNode.ps1` script we use `mcr.microsoft.com/oss/kubernetes/pause:3.6`:
https://github.com/kubernetes-sigs/sig-windows-tools/blob/d744f5488dd350fa967b3920d698b268e214e14d/hostprocess/PrepareNode.ps1#L66

This raises several questions:
- Which would be the right repo/image for windows? `registry.k8s.io/pause` or `mcr.microsoft.com/oss/kubernetes/pause`
- Should we make the image configurable? This would enable us to easily align with the version used for kubelet for linux. In kubelet 1.27.2 this is `registry.k8s.io/pause:3.9`

**Comment by jsturtevant** [comment]
> * Which would be the right repo/image for windows? `registry.k8s.io/pause` or `mcr.microsoft.com/oss/kubernetes/pause`

they are both built from the same source.  The difference is that the mcr.microsoft.com version has binaries signed by Microsoft.  We typically reference the registry.k8s.io registries in the kuberentes repos.

**Comment by jsturtevant** [comment]
I am not certian but I don't think `'--pod-infra-container-image=mcr.microsoft.com/oss/kubernetes/pause:3.6 ` is used any more, the containerd configuration is what is used when deployed with containerd

**Comment by jsturtevant** [comment]
> will be removed in a future release. Image garbage collector will get sandbox image information from CRI.

We should probably remove it since it is depreciated.  That way we are proactive on it.

**Comment by Mik4sa** [comment]
I'm unsure, but I think we can't remove it right now:
https://github.com/kubernetes/kubernetes/pull/118544
