### ISSUE TITLE
Steps to integrate kube-proxy into kubeadm initialization

### ISSUE THREAD

**Issue by Mik4sa** [kubernetes-sigs/sig-windows-tools#324]
While looking through the repository I found this:
https://github.com/kubernetes-sigs/sig-windows-tools/blob/d744f5488dd350fa967b3920d698b268e214e14d/hostprocess/README.md?plain=1#L16-L18

Which steps/prerequisites are needed so we can start with it?
Atleast for flannel, once #314 is merged, I feel like we are at a good point to start.

Do you agree?

**Comment by jsturtevant** [comment]
This document outlines the required steps to improve this in kube-proxy to not be CNI dependent: https://docs.google.com/document/d/1A6Gkyx5EvL86Z4L2P4sxnk9HQjdRgnLXvBg6tIMDB3s/edit

In addition, we would need:

-  a way to build kube-proxy as an image from upstream. This has been tried a few times: https://github.com/kubernetes/kubernetes/pull/109939 but has some challenges.  One other approach would be to build it via scripts here and publish it to k8s repository.
- changes to kubeadm to install kube-proxy
