### ISSUE TITLE
missing flannel image "sigwindowstools/flannel:v0.21.5-hostprocess"

### ISSUE THREAD

**Issue by Liran-Dobrish** [kubernetes-sigs/sig-windows-tools#327]
**Describe the bug**
cannot follow the flannel guide as the images is missing

**To Reproduce**
run the flannel guide

**Expected behavior**
to work...

**Kubernetes (please complete the following information):**
 - Windows Server version: N/A
 - Kubernetes Version: N/A
 - CNI: N/A

**Additional context**

**Comment by Mik4sa** [comment]
Please have a look at #319
