### ISSUE TITLE
How to set up the Proxy for Windows for containerd?

### ISSUE THREAD

**Issue by kkbruce** [kubernetes-sigs/sig-windows-tools#339]
I've successfully added Windows to Kubernetes, but running into issues with containerd and Proxy on Windows. Do you know if anyone has experience with this?

Problem: https://github.com/containerd/containerd/issues/8846

**Comment by davidgiga1993** [comment]
We're facing the same issues. Did you find any solution?
It doesn't work even with HTTPS_PROXY set:
```
(Get-Process containerd).StartInfo.Environment

Key                     Value
---                     -----
HTTP_PROXY              http://corporateproxy.net:9400
HTTPS_PROXY             http://corporateproxy.net:9400
NO_PROXY                172.20.0.0/16,localhost,127.0.0.1,169.254.169.254,.internal,.eu-central-1.ek...
```
