### ISSUE TITLE
Documentation points to image that doesn't exist yet

### ISSUE THREAD

**Issue by MarkBoote** [kubernetes-sigs/sig-windows-tools#343]
**Describe the bug**
Trying to update our windows nodes following the instructions at https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/guides/flannel.md

**To Reproduce**
controlPlaneEndpoint=$(kubectl get configmap -n kube-system kube-proxy -o jsonpath="{.data['kubeconfig\.conf']}" | grep server: | sed 's/.*\:\/\///g')
kubernetesServiceHost=$(echo $controlPlaneEndpoint | cut -d ":" -f 1)
kubernetesServicePort=$(echo $controlPlaneEndpoint | cut -d ":" -f 2)
curl -L https://raw.githubusercontent.com/kubernetes-sigs/sig-windows-tools/master/hostprocess/flannel/flanneld/flannel-overlay.yml | sed 's/FLANNEL_VERSION/v0.21.5/g' | sed "s/KUBERNETES_SERVICE_HOST_VALUE/$kubernetesServiceHost/g" | sed "s/KUBERNETES_SERVICE_PORT_VALUE/$kubernetesServicePort/g" | kubectl apply -f -

**Expected behavior**
Kind of hope https://hub.docker.com/r/sigwindowstools/flannel/tags?page=1&name=v0.21.5 would actually exist, what with it being referenced in the documentation.

**Kubernetes (please complete the following information):**
 - Windows Server version: 2019
 - Kubernetes Version: 1.28.0
 - CNI: flannel

**Additional context**
Just once it would be nice to be able to upgrade flannel on 'doze without tearing my hair out.

**Comment by Mik4sa** [comment]
Please build your own image, see https://github.com/kubernetes-sigs/sig-windows-tools/issues/336#issuecomment-1633854019

**Comment by MarkBoote** [comment]
> Please build your own image, see [#336 (comment)](https://github.com/kubernetes-sigs/sig-windows-tools/issues/336#issuecomment-1633854019)

Thanks for the response.

Have burnt most of the day trying to build our own image, buildx doesn't seem at all happy with either harbor or sonatype...
Gave up trying with those & it seemed to work fine with my private repo on dockerhub.

I'm clearly doing something wrong, downloaded the flannel-overlay.yml, set KUBERNETES_SERVICE_HOST & KUBERNETES_SERVICE_PORT and modified the image to point at the one I built.

It files to create the network, struggling to understand why:
Copying SDN CNI binaries to host


    Directory: C:\opt\cni


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       09/02/2023     11:51                bin
copy flannel config


    Directory: C:\etc


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       09/02/2023     11:51                kube-flannel


    Directory: C:\etc\kube-flannel


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       29/08/2023     17:10            108 net-conf.json


    Directory: C:\C\c7f3b6920d1d69cbd55154e624518f2101d0bd1c5b1ebcd4791a34b3cfafdcce\mounts\kube-flannel


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       29/08/2023     17:10                ..2023_08_29_16_10_13.3511212281
d----l       29/08/2023     17:10                ..data
-a---l       29/08/2023     17:10              0 cni-conf.json
-a---l       29/08/2023     17:10              0 net-conf.json
update cni config


    Directory: C:\etc\cni


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       09/02/2023     11:51                net.d
add route
The route addition failed: The object already exists.

envs
kube-flannel-ds-windows-amd64-9pj6n
kube-flannel
Starting flannel
I0829 17:10:51.487332    3824 main.go:211] CLI flags config: {etcdEndpoints:http://127.0.0.1:4001,http://127.0.0.1:2379 etcdPrefix:/coreos.com/network etcdKeyfile: etcdCertfile: etcdCAFile: etcdUsername: etcdPassword: version:false kubeSubnetMgr:true kubeApiUrl: kubeAnnotationPrefix:flannel.alpha.coreos.com kubeConfigFile: iface:[192.168.1.94] ifaceRegex:[] ipMasq:false ifaceCanReach: subnetFile:/run/flannel/subnet.env publicIP: publicIPv6: subnetLeaseRenewMargin:60 healthzIP:0.0.0.0 healthzPort:0 iptablesResyncSeconds:5 iptablesForwardRules:true netConfPath:/etc/kube-flannel/net-conf.json setNodeNetworkUnavailable:true useMultiClusterCidr:false}
W0829 17:10:51.499936    3824 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0829 17:10:51.520129    3824 client_config.go:622] error creating inClusterConfig, falling back to default config: open /var/run/secrets/kubernetes.io/serviceaccount/token: The system cannot find the path specified.
E0829 17:10:51.531215    3824 main.go:228] Failed to create SubnetManager: fail to create kubernetes config: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable

**Comment by MarkBoote** [comment]
> Please build your own image, see [#336 (comment)](https://github.com/kubernetes-sigs/sig-windows-tools/issues/336#issuecomment-1633854019)

Built my own image, but still had problems starting flannel on windows.

W0829 17:10:51.499936 3824 client_config.go:617] Neither --kubeconfig nor --master was specified. Using the inClusterConfig. This might not work.
W0829 17:10:51.520129 3824 client_config.go:622] error creating inClusterConfig, falling back to default config: open /var/run/secrets/kubernetes.io/serviceaccount/token: The system cannot find the path specified.
E0829 17:10:51.531215 3824 main.go:228] Failed to create SubnetManager: fail to create kubernetes config: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable


This turns out to be an issue with containerd.

Existing cluster was running containerd 1.6.22, which gives the above error. I did try updating to 1.7.5, but bumped into issues with flannel getting 'Access Denied' to the etc & opt folders.

Built a lab cluster to reproduce, stopping containerd service, deleting program files/containerd, /etc & /opt folders then installing containerd 1.7.1, everything seems to start without problems.

Might be worth making a note in the docs that latest will NOT work with containerd < 1.7.
