### ISSUE TITLE
Unable to deploy flannel

### ISSUE THREAD

**Issue by oscgu** [kubernetes-sigs/sig-windows-tools#357]
**Describe the bug**
Whenever I try to deploy flannel it keeps crash looping with the following error:

`W0104 05:45:01.747597    3296 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0104 05:45:01.748130    3296 client_config.go:622] error creating inClusterConfig, falling back to default config: open /var/run/secrets/kubernetes.io/serviceaccount/token: The system cannot find the path specified.
E0104 05:45:01.749443    3296 main.go:226] Failed to create SubnetManager: fail to create kubernetes config: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable`

Setting the KUBERNETES_MASTER env variable does nothing.

**To Reproduce**
Build the flannel image, adjust the place-holders in the deployment file and apply it.

**Expected behavior**
No crash loop

**Kubernetes (please complete the following information):**
 - Windows Server version: Windows Server 2019 Datacenter Evaluation
 - Kernel: 10.0.17763.737
 - Kubernetes Version: 1.27.3
 - CNI: flannel 0.24.0
 - Containerd: 1.7.6

**Additional info**
It's a mixed cluster (linux & windows)
Same issue when using Containerd 1.7.11

**Comment by k8s-ap** [comment]
Any solution to this problem?
I am having the same issue.

**Comment by cyqsimon** [comment]
After some searching around, this looks to be the actual issue. Posting for anyone who lands here.
