### ISSUE TITLE
How to use host's environment variables in the hostprocess container

### ISSUE THREAD

**Issue by IndCheung** [kubernetes-sigs/sig-windows-tools#363]
I created a Flannel container using the hostprocess mode, but I found that after Flannel starts, it will call Powershell to execute some commands. However, the hostprocess container seems to not be able to share environment variables with the host, so executing the Powershell command in Flanneldexe reported an error. How do you solve this problem?

Note: I used the following base image to build the image: https://github.com/microsoft/windows-host-process-containers-base-image

**Comment by jsturtevant** [comment]
you can use the Pod specs Environment variables to map in environment variables needed

**Comment by IndCheung** [comment]
您好，我已收到您的邮件，我会尽快给您回复。谢谢！

**Comment by IndCheung** [comment]
您好，我已收到您的邮件，我会尽快给您回复。谢谢！
