### ISSUE TITLE
kubectl port-forward can hang

### ISSUE THREAD

**Issue by claudiubelu** [kubernetes-sigs/sig-windows-tools#5]
There is a scenario in which ``kubectl port-forward`` will not behave as expected, which also leads to the failure of the following tests:

    [sig-cli] Kubectl Port forwarding [k8s.io] With a server listening on localhost [k8s.io] that expects NO client request should support a client that connects, sends DATA, and disconnects
    [sig-cli] Kubectl Port forwarding [k8s.io] With a server listening on 0.0.0.0 [k8s.io] that expects NO client request should support a client that connects, sends DATA, and disconnects

Steps to reproduce this issue:

    kubectl create namespace ns2
    kubectl create -f port_fw2.yaml  # [1]
    kubectl port-forward -n ns2 pod/pfpod 9992:80 &
    nc 127.0.0.1 9992  # this will output a number of x characters, and will hang.
    kubectl logs -n ns2 pf/pod -c portforwardtester

Looking through the logs, the server lingers (making sure that all the data has been sent) before it closes the socket. I've added timestamps to the server's output:

    Accepted client connection
    Shutting down connection at 2019-07-15 17:12:38.7661425 +0000 GMT m=+516.300379001. Lingering...
    After Lingering... 2019-07-15 17:12:39.4661261 +0000 GMT m=+517.000363301
    Done at 2019-07-15 17:12:39.9686087 +0000 GMT m=+517.502868501

[1] https://paste.ubuntu.com/p/bW4mpYKV8W/

This issue was first signaled here: https://github.com/kubernetes/kubernetes/issues/78857#issuecomment-511489858

**Comment by benmoss** [comment]
I tried using your pause image (`claudiubelu/wincat:1.0`) and all four tests passed on my cluster.

**Comment by bclau** [comment]
Can you describe your cluster?  (Kubernetes version, branch from which the tests were built from, windows node version, windows docker version)

**Comment by benmoss** [comment]
Sorry, I spoke too soon when I said it all passed. Let me look into this further.

**Comment by benmoss** [comment]
Okay, sorry for the mixup. Your pause image fails for me too, but I built my own image at `benmoss/wincat:latest` that passes all 8 tests. Can you give that a shot and see if it works on your cluster too?

I have a hunch that if you built your docker image using the Dockerfile in this repo that you would have actually gotten a `wincat.exe` from the master branch rather than from my PR (before it was merged). The Dockerfile builds wincat from source but by `git clone`-ing it inside the Docker image rather than copying it from the host.

My cluster's master is running 1.14.1, my Windows node is 1.15.3.

**Comment by benmoss** [comment]
@bclau Is this still an issue for you?

**Comment by vasily-codefresh** [comment]
@benmoss I believe, I can reproduce it here. Windows 1903, Kubernetes client 1.16.2.

from time to time `kubectl port-forward` just hangs and the only way to get it working is to restart it.

please let me know if I can provide additional details.

**Comment by benmoss** [comment]
@vasily-codefresh what pause image are you using? Does it hang immediately after you start it or only after it's been running/proxying for a while?

**Comment by vasily-codefresh** [comment]
@benmoss I actually experience this will all images I use. usually this happens after some time, but it may vary from several seconds to several minutes.

I'm pretty sure it's Windows-specific, because on Linux same port-forward works without hanging.

**Comment by benmoss** [comment]
I mean the pause image, not the pod container image. If you go on your Windows node and do `docker images` you'll likely have one like `mcr.microsoft.com/k8s/core/pause:1.2.0`. I just want to try to confirm which version of `wincat` you are using.

**Comment by vasily-codefresh** [comment]
@benmoss hm, to be clear I have Windows locally, not remotely. no any `pause` image on my workstation. remote side is a cloud k8s installation (on top of Linux), so I don't have direct access to Docker, I believe.

if there's something else I can look up to help you spotting this leopard, give me a note. thanks.

**Comment by vasily-codefresh** [comment]
heh, for me it was Windows' firewall. I explicitly whitelisted `kubectl` and everything seems fine yet (or at least much better than it was).

@benmoss thanks for your patience!

**Comment by cretz** [comment]
I am experiencing this as well and my kubectl is open via windows firewall. My issue was access over localhost ipv6 instead of just ipv4. Once I set `--address 127.0.0.1` which forced my browser to use that for `localhost`, there were no more issues.
