### ISSUE TITLE
Please update instructions for servercore installations

### ISSUE THREAD

**Issue by artisticcheese** [kubernetes-sigs/sig-windows-tools#50]
As part of installation for environment variables to take effect it's advised to start a new powershell session to perform `JOIN`. Issue is that if you are in servercore console you can not create a new session easily. The only option is either log off or reboot. Can description be modified to note that logoff is required for server core installs.

**Comment by benmoss** [comment]
hey @artisticcheese, we're removing these scripts and updating the documentation. A preview of the documentation is available here: https://deploy-preview-19217--kubernetes-io-vnext-staging.netlify.com/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/

**Comment by artisticcheese** [comment]
Wow, new way to onboard (via `kubadm` tool) is awesome.  Is it something can be done with 17.4 or have to use 18?

**Comment by benmoss** [comment]
It will work with versions >= 1.17.0

**Comment by artisticcheese** [comment]
Why also curl is used for downloading binaries instead of powershell since `curl` does not come by default with Windows install. Should have been `Invoke-Webrequest -Outfile`

**Comment by neolit123** [comment]
@artisticcheese 
previously @benmoss mentioned that nowadays `curl` is installed on Windows Server, yet i'm not sure if all versions have it.

what version are you seeing `curl` missing in?

**Comment by artisticcheese** [comment]
Yes, to my surprise I found that curl.exe is now part of SAC channel and Windows 2019. I was unaware of it until today since it's not Microsoft binaries and strange to see them part of OS deployment. NVM.

**Comment by benmoss** [comment]
Yeah, it's been part of Windows since 1803
