### ISSUE TITLE
Windows nodes do not come back after reboot

### ISSUE THREAD

**Issue by benmoss** [kubernetes-sigs/sig-windows-tools#52]
We disabled automatic reboots for our e2e clusters in #51, but we should make it so even if a machine reboots that kubelet / docker / wins all are set to automatically start so that a machine can be rebooted.

**Comment by giskou** [comment]
Windows workers that reboot seem to have kubelet / docker / wins running but flannel fails.
A docker nat network is created [here](https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/kubeadm/scripts/PrepareNode.ps1#L56) and according to the [official documentation](https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/network-drivers-topologies) that network is removed on reboot ([Github issue for docker-win](https://github.com/docker/for-win/issues/3076)).
Is there a workaround for this?

**Comment by benmoss** [comment]
That's pretty frustrating, I don't think there's a workaround right now

**Comment by lippertmarkus** [comment]
Running 
```
docker network create -d nat host
```
after reboot works for me. All pods are correctly starting up automatically afterwards.
Maybe as a temporary workaround we could add that as a startup task?

**Comment by artisticcheese** [comment]
`Host` network disappearing for me on reboot even with `docker network create -d nat host`. Not sure how this is keep getting closed?

**Comment by artisticcheese** [comment]
This breaks name resolution with DNS service. One has to restart `rancher-wins` service to make DNS to work again. But yet again, once you do that DNS starts working but kube-api (`kubernetes`) service stops working. It's just a complete mess.

**Comment by lippertmarkus** [comment]
@artisticcheese DNS works for me right after restarting my windows node, even without manual restart of `rancher-wins`. Did you recreate your cluster with changes from #66 or at least included the change (the docker network creation command) in `C:\k\StartKubelet.ps1` in your existing cluster?

**Comment by artisticcheese** [comment]
Yes, I fixed it with manual changed to `StartKubelet.ps1` as you mentioned. Without it restarting rancher fixes DNS but breaks API server. 
As of right now
1.18.1 is not compatible with Windows 1909 or 1903 and broken out of the box with Windows 2019. How did it reach stable I don't understand since none of those issues exists with 1.17.4 I've been running before

**Comment by lippertmarkus** [comment]
@artisticcheese as far as I can see this is only intended for 1809 (Windows Server 2019 LTSC). The docker images of flannel or kube-proxy are based on that.

**Comment by artisticcheese** [comment]
Yes but 1.17.4 worked fine on SAC channels too. So new version of Kubernetes essentially have less support for newer versions of Windows then old one.

**Comment by benmoss** [comment]
Please instead of complaining you can volunteer to add 1909 and 1903 support yourself. It should not be very hard, I think it just requires building the kube-proxy and flannel images for those OSes.

**Comment by daschott** [comment]
Just thinking out loud here, would it be possible to make this `host` network of type `l2bridge` or `overlay`? That way it would be persisted across reboot. The script also creates a network of the corresponding type called `External`. Could this (+ any references to its name) simply be renamed to `host`? Has anyone tried this?
