### ISSUE TITLE
kubeadm-e2e: investigate failing tests

### ISSUE THREAD

**Issue by neolit123** [kubernetes-sigs/sig-windows-tools#56]
EDIT: we had discussions on slack:
https://kubernetes.slack.com/archives/C0SJ4AFB7/p1584740410152900

and the network failures are apparently caused by a Windows bug when executing 32bit apps on 64bit images that have PATCH level version differences with the host, that should be resolved once we have the latest agnhost image at the `e2eteam` account:
https://hub.docker.com/u/e2eteam

---------

latest kubeadm e2e test run reports the following failures.
some of them might be flakes.

https://k8s-testgrid.appspot.com/sig-windows#kubeadm-windows-gcp-k8s-stable

> [k8s.io] Container Lifecycle Hook when create a pod with lifecycle hook should execute poststart http hook properly [NodeConformance] [Conformance]

TODO

> [k8s.io] Container Lifecycle Hook when create a pod with lifecycle hook should execute prestop http hook properly [NodeConformance] [Conformance]

TODO

> [k8s.io] Docker Containers should use the image defaults if command and args are blank [NodeConformance] [Conformance]

the test is here:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/docker_containers.go#L33-L50
this could be caused by flake when polling to fetch the logs, or simply because the Agnhost container for windows is not printing "Paused"?

> [sig-api-machinery] Aggregator Should be able to support the 1.10 Sample API Server using the current Aggregator [Conformance]

this one is now disabled via a SKIP=...Aggregator |....
https://github.com/kubernetes-sigs/sig-windows-tools/pull/55

> [sig-network] Services should be able to change the type from ExternalName to ClusterIP [Conformance]

TODO

> [sig-network] Services should be able to change the type from ExternalName to NodePort [Conformance]

TODO

> [sig-network] Services should be able to create a functioning NodePort service [Conformance]

TODO

> [sig-network][sig-windows] Networking Granular Checks: Pods should function for node-pod communication: udp

for the sig-network* failures we are suspecting a potential agnhost issue, because benmoss verified that the underlying test details work with a simple web server.

> [sig-storage] HostPath should support r/w [NodeConformance]

this might be caused by a missing /tmp on the windows nodes:
https://github.com/kubernetes/kubernetes/blob/1bb68a2cde08e39875f8e4f53bf429e14438835e/test/e2e/common/host_path.go#L64-L89

/kind failing-test
/priority important-soon
/assign @neolit123 @benmoss

**Comment by claudiubelu** [comment]
> > [k8s.io] Docker Containers should use the image defaults if command and args are blank [NodeConformance] [Conformance]
> 
> the test is here:
> https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/docker_containers.go#L33-L50
> this could be caused by flake when polling to fetch the logs, or simply because the Agnhost container for windows is not printing "Paused"?

It should. It's been printing Paused since a while now (see agnhost/pause changes): https://github.com/kubernetes/kubernetes/pull/79142
But it depends. How new are the tests you're running / what agnhost version are the tests using?

> 
> > [sig-network][sig-windows] Networking Granular Checks: Pods should function for node-pod communication: udp
> 
> for this issue claudiubelu suggested to try these steps:
> [kubernetes/kubernetes#83739](https://github.com/kubernetes/kubernetes/issues/83739)

I've actually created a new test that specifically targets the packet fragmentation issue, which you should take a look at / run: https://github.com/kubernetes/kubernetes/pull/83680

> 
> > [sig-storage] HostPath should support r/w [NodeConformance]
> 
> this might be caused by a missing /tmp on the windows nodes:
> https://github.com/kubernetes/kubernetes/blob/1bb68a2cde08e39875f8e4f53bf429e14438835e/test/e2e/common/host_path.go#L64-L89

Most likely. We're creating that folder in all test runs.

**Comment by neolit123** [comment]
> It should. It's been printing Paused since a while now (see agnhost/pause changes): kubernetes/kubernetes#79142
But it depends. How new are the tests you're running / what agnhost version are the tests using?

the `[k8s.io] Docker Containers` and `[sig-storage] HostPath ` ... appear to be flakes.

https://k8s-testgrid.appspot.com/sig-windows#kubeadm-windows-gcp-k8s-stable

i think these two can be fixed if we bump the poll timeout from 3 seconds:
```
[sig-storage] HostPath should support subPath [NodeConformance]
[sig-storage] HostPath should support r/w [NodeConformance]
```

> I've actually created a new test that specifically targets the packet fragmentation issue, which you should take a look at / run: kubernetes/kubernetes#83680

:+1:
