### ISSUE TITLE
Error when calling kubecluster.ps1 for overlay connection. 

### ISSUE THREAD

**Issue by vidushv** [kubernetes-sigs/sig-windows-tools#58]
I'm running the command:  `.\kubecluster.ps1 -join -configFile .\kubeclustervxlan.json`

Error:
```
Waiting for service [FlannelD] to be running
Waiting for the Network (vxlan0) to be created by flanneld
You cannot call a method on a null-valued expression.
At C:\Users\Administrator\scripts\KubeClusterHelper.psm1:401 char:12
+     return $sourceVipJSONData.ip4.ip.Split("/")[0]
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

```

This produces occasionally, sometimes running reset and then attempting to join again works so the issue is not very reproducible. It causes kube-proxy to not start.

SourceVip.json:
```
{
    "code": 100,
    "msg": "failed to allocate for range 0: 10.244.6.3 has been allocated to dummy, duplicate allocation is not allowed"
}
```

**Comment by neolit123** [comment]
hi ` kubecluster.ps1` is deprecated and will be removed perhaps shortly after the 1.18 release.
we are now moving to use https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/kubeadm/scripts/PrepareNode.ps1

but the docs for that are not officially released yet:
https://github.com/kubernetes/website/tree/dev-1.18/content/en/docs/tasks/administer-cluster/kubeadm
see adding/upgrading-windows* nodes.
