### ISSUE TITLE
Node join issue

### ISSUE THREAD

**Issue by ukreddy-erwin** [kubernetes-sigs/sig-windows-tools#64]
Windows nodes, can't join to network with Calico.
It seems, it is supported only flannel.As the join parameters is asking for flannel details.

And also,
After joining node, if I restart the machine-(windows node). It is not recognizing the node again.
It is not showing the updated status after the machine is restarted.

**Comment by neolit123** [comment]
> Windows nodes, can't join to network with Calico.
It seems, it is supported only flannel.As the join parameters is asking for flannel details.

hi, yes Calico is not supported for the time being, as AFAIK Calico itself does not support Windows hosts yes. Flannel does.

> After joining node, if I restart the machine-(windows node). It is not recognizing the node again.
It is not showing the updated status after the machine is restarted.

for this see:
https://github.com/kubernetes-sigs/sig-windows-tools/issues/52
let's continue the discussion there.

/close
