### ISSUE TITLE
failed to get default interface: no index found for interface ""

### ISSUE THREAD

**Issue by xmapst** [kubernetes-sigs/sig-windows-tools#68]
kubernetes 1.18.1
docker 19.03.5
```
����: 
ģ�顰hns���е�ĳЩ�������������ư���δ��׼�Ķ��ʣ���Щ���ʿ��ܵ�����Щ���������ױ����֡���Ҫ���Ҿ���δ��׼�Ķ��ʵ�����
����ʹ�� Verbose �����ٴ����� Import-Module ����й���׼�Ķ����б��������� Get-Verb��
Invoke-HnsRequest : @{Error=�Ҳ����������� ; ErrorCode=2151350278; Success=False}
����λ�� C:\k\flannel\hns.psm1:233 �ַ�: 16
+ ...      return Invoke-HnsRequest -Method POST -Type networks -Data $Json ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-HNSRequest
 
FATA[2020-04-20T18:31:47+08:00] rpc error: code = Internal desc = could not create IP forward entry: The object already exists. 
I0420 18:31:48.571762    2888 main.go:518] Determining IP address of default interface
E0420 18:31:48.942744    2888 main.go:204] Failed to find any valid interface to use: failed to get default interface: no index found for interface ""
```

**Comment by neolit123** [comment]
hi, what is the windows version?

/triage needs-information

**Comment by xmapst** [comment]
> hi, what is the windows version?
> 
> /triage needs-information

Microsoft Windows [版本 10.0.17763.1158]

**Comment by nocanstillbb** [comment]
```
chcp 65001
#will solve inteface name contains utf8 char
```

**Comment by xmapst** [comment]
> ```
> chcp 65001
> #will solve inteface name contains utf8 char
> ```

to no avail

**Comment by nocanstillbb** [comment]
> > ```
> > chcp 65001
> > #will solve inteface name contains utf8 char
> > ```
> 
> to no avail

did you fix this problem?

**Comment by xmapst** [comment]
> > > ```
> > > chcp 65001
> > > #will solve inteface name contains utf8 char
> > > ```
> > 
> > 
> > to no avail
> 
> did you fix this problem?

Use English version system

**Comment by xunchangguo** [comment]
just on cn windows

**Comment by Lwxiang** [comment]
anyone solve this problem?

**Comment by Lwxiang** [comment]
I have solved this, in windows server, before you start any service includes docker, set "controll panel" -> "region" -> "administrative" -> "change system locale..." -> check the option "Use Unicode UTF-8 for worldwide language support"
then reboot

it makes the whole system default to be chcp65001

**Comment by jsturtevant** [comment]
@Lwxiang Thanks for the update, this does look like a encoding issue.

/close

**Comment by real-zony** [comment]
> I have solved this, in windows server, before you start any service includes docker, set "controll panel" -> "region" -> "administrative" -> "change system locale..." -> check the option "Use Unicode UTF-8 for worldwide language support" then reboot
> 
> it makes the whole system default to be chcp65001

It's working, thx.
