### ISSUE TITLE
"Error response from daemon: network host not found" (with latest docs)

### ISSUE THREAD

**Issue by Grovespaz** [kubernetes-sigs/sig-windows-tools#88]
I've followed all the steps on [this page](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/) but they don't seem to be up-to-date / correct.
The flannel and kube-proxy containers won't start on Windows.
The flannel container has the following error message:

>   Warning  FailedCreatePodSandBox  3m (x12 over 3m)     kubelet, win-tplojsb0jn5  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-flannel-ds-windows-amd64-wc22r": Error response from daemon: network host not found

The kube-proxy container has the following error message:
>   Warning  FailedCreatePodSandBox  10m                  kubelet, win-tplojsb0jn5  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "76e22248a4c48eac683fad6f12c5d16077a1a1d0e58ffc499e12260e0ef87b85" network for pod "kube-proxy-windows-j2chr": networkPlugin cni failed to set up pod "kube-proxy-windows-j2chr_kube-system" network: error while GETHNSNewtorkByName(flannel.4096): Network flannel.4096 not found

Kubernetes Version:
v1.18.2

Windows Version:
Windows Server 2019 with latest updates

If there's any other information I can provide, please let me know

**Comment by lippertmarkus** [comment]
Try to run `docker network create -d nat host`

**Comment by Grovespaz** [comment]
That does indeed seem to work, until the node is rebooted after which it is needed again.

Is there a step I missed or that's missing from the docs?

**Comment by Grovespaz** [comment]
Although this gets past this error, there still seems to be a network-related issue. All windows pods crash with exit code -1073741510 which points me towards https://github.com/kubernetes/kubernetes/issues/72696 and https://github.com/microsoft/SDN/issues/298 , but those solutions don't seem to apply.

**Comment by lippertmarkus** [comment]
I fixed this in #66 so if you would start over again with the newest `PrepareNode.ps1` script it should work. If you don't want to start over you could just add the changes of the PR manually to `C:\k\StartKubelet.ps1`.

No clue about the network related issue, maybe the logs of the kube-flannel and kube-proxy containers would help.

**Comment by Grovespaz** [comment]
Thanks, indeed this is a duplicate of #52 and fixed in #66, thank you.
I'll close this and create a new issue for the current network issues I'm experiencing currently.
