### ISSUE TITLE
after restart computer, Network flannel.4096 not found

### ISSUE THREAD

**Issue by nocanstillbb** [kubernetes-sigs/sig-windows-tools#89]
### description  
before restart computer ,windows node run well , kubelet and kube-proxy not print error logs
### kubelet logs
```
Log file created at: 2020/05/17 17:03:16
Running on machine: WIN-PB8V19E08A7
Binary: Built with gc go1.13.9 for windows/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0517 17:03:16.539124    6948 server.go:754] kubelet needs to run as uid `0`. It is being run as -1
E0517 17:03:16.602165    6948 file_unsupported.go:28] Watching source file is unsupported in this build
E0517 17:03:16.972802    6948 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
E0517 17:03:17.142229    6948 kubelet.go:1845] skipping pod synchronization - [container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]
E0517 17:03:17.143226    6948 processstarttime.go:43] Could not get process start time, could not read /proc: CreateFile /proc: The system cannot find the file specified.
E0517 17:03:17.362888    6948 remote_runtime.go:495] ListContainerStats with filter &ContainerStatsFilter{Id:,PodSandboxId:,LabelSelector:map[string]string{},} from runtime service failed: rpc error: code = Unknown desc = hcsshim::OpenComputeSystem 3e2ee0013bb64a6296ef53a11119144297c64c083a5b4f3a16eb3f8151fa6cdf: A virtual machine or container with the specified identifier does not exist.
E0517 17:03:17.362888    6948 eviction_manager.go:255] eviction manager: failed to get summary stats: failed to list pod stats: failed to list all container stats: rpc error: code = Unknown desc = hcsshim::OpenComputeSystem 3e2ee0013bb64a6296ef53a11119144297c64c083a5b4f3a16eb3f8151fa6cdf: A virtual machine or container with the specified identifier does not exist.
E0517 17:03:17.377879    6948 cni.go:364] Error adding kube-system_kube-proxy-windows-htp85/a3bfa027b8fe55173dcfff3a9cc47a6380665d6bb69e87fdb68ca91d2be6bd37 to network flannel/flannel.4096: error while GETHNSNewtorkByName(flannel.4096): Network flannel.4096 not found
E0517 17:03:17.377879    6948 cni_windows.go:59] error while adding to cni network: error while GETHNSNewtorkByName(flannel.4096): Network flannel.4096 not found
```

**Comment by WeetA34** [comment]
Hello
same issue for me with kubernetes 1.18.3 and windows server 1903
Rgds

**Comment by kkobayachi** [comment]
Hi,
same issue here too kubernetes 1.18.3 and server windows server 1809
tks

**Comment by keyva** [comment]
Ran in to the same issue. Below is a workaround - 

Apparently the HNSNetwork component on the Windows worker node needs to be deleted manually, as its remnants still stay registered on the master node even after deleting the windows worker node from the cluster. 

To resolve, here is what was done (after removing worker node from cluster) - 

1) On the Windows worker node, run in powershell = _Get-HNSNetwork | Remove-HNSNetwork_

2) On the Master node, _curl -L https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/kube-proxy.yml | sed 's/VERSION/v**1.18.0**/g' | kubectl **delete** -f -_

You may have to apply the specific command for your version of k8s.

3) On the Master node, _kubectl **delete** -f https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/flannel-overlay.yml_

4) On the Master node, _curl -L https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/kube-proxy.yml | sed 's/VERSION/v1.18.0/g' | kubectl **apply** -f -_

5) On the Master node, _kubectl **apply** -f https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/flannel-overlay.yml_

6) On the Master node, _kubeadm token create --print-join-command_  (copy the output)

7) On the Windows (soon to be) worker node, in powershell =  _Remove-NetFirewallRule_

8) Remove the entire folder under C:\k and C:\var and C:\etc , and run the .\PrepareNode.ps1 script that was downloaded from https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/PrepareNode.ps1 

9) On the Windows (soon to be) worker node, paste the output from step 6 above - i.e. join the Worker node again.

10) Try your windows app deployment (e.g. IIS) 

I presume that it's a minor change somewhere in the latest sig-windows code, but I did not have the time to dig in to modifying/updating it. Obviously, the above solution cannot scale if clients need to update/reboot their Windows worker nodes frequently. As a temporary patch thought, we can surely automate it.

**Comment by kkobayachi** [comment]
Hello,
I did the troubleshooting and diagnosed that the error presented is because after restarting the windows server the nat network interface created "docker network create -d nat host" by the script preparenode.ps1 missing, this appears to be an unresolved windows bug yet.
If the interface is created again, the pods start successfully.

**Comment by michaelbeckersgit** [comment]
Hello,

Can somebody please look at this, it has been blocking me for a while now. We cannot work like this, the solution is completely unusable.

**Comment by oneoneonepig** [comment]
### How to recreate
1. Follow the guide on [Adding Windows nodes](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/) provided by Kubernetes Doc
2. Reboot the Windows Node
3. All Pods scheduled on Windows cannot be re-created, stucking at the status **Error** 
```
$ kubectl get pod  -o wide
NAME                               READY   STATUS    RESTARTS   AGE   IP            NODE             NOMINATED NODE   READINESS GATES
linux-webserver-68f9fdbc79-gxv9w   1/1     Running   0          13h   10.244.0.16   k8s-master       <none>           <none>
linux-webserver-68f9fdbc79-kcblh   1/1     Running   0          13h   10.244.0.14   k8s-master       <none>           <none>
linux-webserver-68f9fdbc79-pw9kf   1/1     Running   0          13h   10.244.0.13   k8s-master       <none>           <none>
linux-webserver-68f9fdbc79-s76bm   1/1     Running   0          13h   10.244.0.15   k8s-master       <none>           <none>
nginx-d46f5678b-ggnqw              1/1     Running   0          20h   10.244.0.12   k8s-master       <none>           <none>
win-webserver-5b9d465b69-55n8w     0/1     Error     1          20h   <none>        k8s-win-worker   <none>           <none>
win-webserver-5b9d465b69-hf6sh     0/1     Error     1          20h   <none>        k8s-win-worker   <none>           <none>
win-webserver-5b9d465b69-jdk9h     0/1     Error     1          20h   <none>        k8s-win-worker   <none>           <none>
win-webserver-5b9d465b69-tx2pb     0/1     Error     1          20h   <none>        k8s-win-worker   <none>           <none>

$ kubectl describe pod win-webserver-5b9d465b69-tx2pb
<partially omitted>
Warning  FailedCreatePodSandBox  5m38s (x3 over 5m44s)  kubelet, k8s-win-worker  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "3cd40d1ec397948af00873e90aa4b54bb3cf3f6aa202453946a6ef2657f17cd2" network for pod "win-webserver-5b9d465b69-tx2pb": networkPlugin cni failed to set up pod "win-webserver-5b9d465b69-tx2pb_default" network: error while GETHNSNewtorkByName(flannel.4096): Network flannel.4096 not found
  Normal   SandboxChanged          68s (x128 over 6m5s)   kubelet, k8s-win-worker  Pod sandbox changed, it will be killed and re-created.
```
### How I fix it
I found out that there is a similar issue https://github.com/kubernetes-sigs/sig-windows-tools/issues/52 and a PR https://github.com/kubernetes-sigs/sig-windows-tools/pull/66, which works for me after manually modifying the files introduced in the PR https://github.com/kubernetes-sigs/sig-windows-tools/pull/66.

It turns out that the Kubernetes Doc [Adding Windows nodes](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/) uses the latest **release** instead of the latest **commit**
(for example, `curl.exe -LO https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/PrepareNode.ps1
.\PrepareNode.ps1 -KubernetesVersion v1.18.0`),
which does not include the fix

For short term, we can manually perform the patch by adding the entries and reboot again to verify if it works
```
$FileContent = Get-Content -Path "/var/lib/kubelet/kubeadm-flags.env"
$global:KubeletArgs = $FileContent.Trim("KUBELET_KUBEADM_ARGS=`"")

$netId = docker network ls -f name=host --format "{{ .ID }}"
if ($netId.Length -lt 1) {
    docker network create -d nat host
}

$cmd = "C:\k\kubelet.exe $global:KubeletArgs --cert-dir=$env:SYSTEMDRIVE\var\lib\kubelet\pki --config=/var/lib/kubelet/config.yaml --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --hostname-override=$(hostname) --pod-infra-container-image=`"mcr.microsoft.com/k8s/core/pause:1.2.0`" --enable-debugging-handlers --cgroups-per-qos=false --enforce-node-allocatable=`"`" --network-plugin=cni --resolv-conf=`"`" --log-dir=/var/log/kubelet --logtostderr=false --image-pull-progress-deadline=20m"

Invoke-Expression $cmd
```

For long term, I recommend that we can update the Kubernetes Doc to use the latest commit, or create a new release on this repo

### Related Issue and PR
https://github.com/kubernetes-sigs/sig-windows-tools/issues/52
https://github.com/kubernetes-sigs/sig-windows-tools/issues/88
https://github.com/kubernetes-sigs/sig-windows-tools/pull/66

**Comment by AMoghrabi** [comment]
Thanks a lot @oneoneonepig !

**Comment by jonaskello** [comment]
Thanks @oneoneonepig! 
Agree that a new release would be really nice. Took me a while to find that this was the problem. Reading github issues it seems to be solved so I was initially really confused. But the script used in the instructions does not include the fix like you say :-).

**Comment by jsturtevant** [comment]
Thanks @oneoneonepig! 

I've cut a release that includes the restart fix: https://github.com/kubernetes-sigs/sig-windows-tools/releases/tag/v0.1.3
