### ISSUE TITLE
Does Docker for Windows Server 2019 support GUI-based applications?

### ISSUE THREAD

**Issue by RedBoneZhang** [kubernetes-sigs/sig-windows-tools#97]
Question:
Does Docker for Windows Server 2019 support GUI-based applications?

I want to run a GUI application desktop(With a 3d map inside) in windows container at windows server host.

**Comment by jsturtevant** [comment]
No GUI is supported. Please direct general windows containers questions to https://github.com/microsoft/Windows-Containers/issues

/close
